// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.11
// source: api/helloworld/payment/payment.proto

package payment

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentRequest) Reset() {
	*x = UpdatePaymentRequest{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentRequest) ProtoMessage() {}

func (x *UpdatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{0}
}

type UpdatePaymentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentReply) Reset() {
	*x = UpdatePaymentReply{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentReply) ProtoMessage() {}

func (x *UpdatePaymentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentReply.ProtoReflect.Descriptor instead.
func (*UpdatePaymentReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePaymentReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type CreatedReconciliationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedTime   string                 `protobuf:"bytes,1,opt,name=CreatedTime,proto3" json:"CreatedTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedReconciliationRequest) Reset() {
	*x = CreatedReconciliationRequest{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedReconciliationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedReconciliationRequest) ProtoMessage() {}

func (x *CreatedReconciliationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedReconciliationRequest.ProtoReflect.Descriptor instead.
func (*CreatedReconciliationRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatedReconciliationRequest) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

type CreatedReconciliationReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReconciliationId int64                  `protobuf:"varint,1,opt,name=ReconciliationId,proto3" json:"ReconciliationId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatedReconciliationReply) Reset() {
	*x = CreatedReconciliationReply{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedReconciliationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedReconciliationReply) ProtoMessage() {}

func (x *CreatedReconciliationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedReconciliationReply.ProtoReflect.Descriptor instead.
func (*CreatedReconciliationReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreatedReconciliationReply) GetReconciliationId() int64 {
	if x != nil {
		return x.ReconciliationId
	}
	return 0
}

type ReconciliationItem struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskName           string                 `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
	ReconciliationNo   string                 `protobuf:"bytes,2,opt,name=ReconciliationNo,proto3" json:"ReconciliationNo,omitempty"`
	ReconciliationDate string                 `protobuf:"bytes,3,opt,name=ReconciliationDate,proto3" json:"ReconciliationDate,omitempty"`
	Amount             float32                `protobuf:"fixed32,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	ActualAmount       float32                `protobuf:"fixed32,5,opt,name=ActualAmount,proto3" json:"ActualAmount,omitempty"`
	Proportion         string                 `protobuf:"bytes,6,opt,name=Proportion,proto3" json:"Proportion,omitempty"`
	HandlerStatus      string                 `protobuf:"bytes,7,opt,name=HandlerStatus,proto3" json:"HandlerStatus,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReconciliationItem) Reset() {
	*x = ReconciliationItem{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationItem) ProtoMessage() {}

func (x *ReconciliationItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationItem.ProtoReflect.Descriptor instead.
func (*ReconciliationItem) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *ReconciliationItem) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *ReconciliationItem) GetReconciliationNo() string {
	if x != nil {
		return x.ReconciliationNo
	}
	return ""
}

func (x *ReconciliationItem) GetReconciliationDate() string {
	if x != nil {
		return x.ReconciliationDate
	}
	return ""
}

func (x *ReconciliationItem) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReconciliationItem) GetActualAmount() float32 {
	if x != nil {
		return x.ActualAmount
	}
	return 0
}

func (x *ReconciliationItem) GetProportion() string {
	if x != nil {
		return x.Proportion
	}
	return ""
}

func (x *ReconciliationItem) GetHandlerStatus() string {
	if x != nil {
		return x.HandlerStatus
	}
	return ""
}

type ListReconciliationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayTime      string                 `protobuf:"bytes,1,opt,name=PlayTime,proto3" json:"PlayTime,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconciliationRequest) Reset() {
	*x = ListReconciliationRequest{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconciliationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconciliationRequest) ProtoMessage() {}

func (x *ListReconciliationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconciliationRequest.ProtoReflect.Descriptor instead.
func (*ListReconciliationRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *ListReconciliationRequest) GetPlayTime() string {
	if x != nil {
		return x.PlayTime
	}
	return ""
}

func (x *ListReconciliationRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type ListReconciliationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ReconciliationItem  `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReconciliationReply) Reset() {
	*x = ListReconciliationReply{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReconciliationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReconciliationReply) ProtoMessage() {}

func (x *ListReconciliationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReconciliationReply.ProtoReflect.Descriptor instead.
func (*ListReconciliationReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *ListReconciliationReply) GetList() []*ReconciliationItem {
	if x != nil {
		return x.List
	}
	return nil
}

type PaymentOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	PaymentType   string                 `protobuf:"bytes,2,opt,name=PaymentType,proto3" json:"PaymentType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentOrderRequest) Reset() {
	*x = PaymentOrderRequest{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentOrderRequest) ProtoMessage() {}

func (x *PaymentOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentOrderRequest.ProtoReflect.Descriptor instead.
func (*PaymentOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentOrderRequest) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PaymentOrderRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

type PaymentOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentOrderReply) Reset() {
	*x = PaymentOrderReply{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentOrderReply) ProtoMessage() {}

func (x *PaymentOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentOrderReply.ProtoReflect.Descriptor instead.
func (*PaymentOrderReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentOrderReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MonitorCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	MonitorType   string                 `protobuf:"bytes,2,opt,name=MonitorType,proto3" json:"MonitorType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorCreateRequest) Reset() {
	*x = MonitorCreateRequest{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorCreateRequest) ProtoMessage() {}

func (x *MonitorCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorCreateRequest.ProtoReflect.Descriptor instead.
func (*MonitorCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{9}
}

func (x *MonitorCreateRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *MonitorCreateRequest) GetMonitorType() string {
	if x != nil {
		return x.MonitorType
	}
	return ""
}

type MonitorCreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorCreateReply) Reset() {
	*x = MonitorCreateReply{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorCreateReply) ProtoMessage() {}

func (x *MonitorCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorCreateReply.ProtoReflect.Descriptor instead.
func (*MonitorCreateReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{10}
}

func (x *MonitorCreateReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MonitorUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonitorNo     string                 `protobuf:"bytes,1,opt,name=MonitorNo,proto3" json:"MonitorNo,omitempty"`
	HandleResult  string                 `protobuf:"bytes,2,opt,name=HandleResult,proto3" json:"HandleResult,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorUpdateRequest) Reset() {
	*x = MonitorUpdateRequest{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorUpdateRequest) ProtoMessage() {}

func (x *MonitorUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorUpdateRequest.ProtoReflect.Descriptor instead.
func (*MonitorUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{11}
}

func (x *MonitorUpdateRequest) GetMonitorNo() string {
	if x != nil {
		return x.MonitorNo
	}
	return ""
}

func (x *MonitorUpdateRequest) GetHandleResult() string {
	if x != nil {
		return x.HandleResult
	}
	return ""
}

type MonitorUpdateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorUpdateReply) Reset() {
	*x = MonitorUpdateReply{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorUpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorUpdateReply) ProtoMessage() {}

func (x *MonitorUpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorUpdateReply.ProtoReflect.Descriptor instead.
func (*MonitorUpdateReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{12}
}

func (x *MonitorUpdateReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MonitorDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorDeleteRequest) Reset() {
	*x = MonitorDeleteRequest{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorDeleteRequest) ProtoMessage() {}

func (x *MonitorDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorDeleteRequest.ProtoReflect.Descriptor instead.
func (*MonitorDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{13}
}

func (x *MonitorDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MonitorDeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorDeleteReply) Reset() {
	*x = MonitorDeleteReply{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorDeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorDeleteReply) ProtoMessage() {}

func (x *MonitorDeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorDeleteReply.ProtoReflect.Descriptor instead.
func (*MonitorDeleteReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{14}
}

func (x *MonitorDeleteReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OrderItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderNo         string                 `protobuf:"bytes,1,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	SenderName      string                 `protobuf:"bytes,2,opt,name=SenderName,proto3" json:"SenderName,omitempty"`
	SenderPhone     string                 `protobuf:"bytes,3,opt,name=SenderPhone,proto3" json:"SenderPhone,omitempty"`
	SenderAddress   string                 `protobuf:"bytes,4,opt,name=SenderAddress,proto3" json:"SenderAddress,omitempty"`
	ReceiverName    string                 `protobuf:"bytes,5,opt,name=ReceiverName,proto3" json:"ReceiverName,omitempty"`
	ReceiverPhone   string                 `protobuf:"bytes,6,opt,name=ReceiverPhone,proto3" json:"ReceiverPhone,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,7,opt,name=ReceiverAddress,proto3" json:"ReceiverAddress,omitempty"`
	ProductType     string                 `protobuf:"bytes,8,opt,name=ProductType,proto3" json:"ProductType,omitempty"`
	ActualFee       string                 `protobuf:"bytes,9,opt,name=ActualFee,proto3" json:"ActualFee,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{15}
}

func (x *OrderItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderItem) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *OrderItem) GetSenderPhone() string {
	if x != nil {
		return x.SenderPhone
	}
	return ""
}

func (x *OrderItem) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *OrderItem) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *OrderItem) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *OrderItem) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *OrderItem) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *OrderItem) GetActualFee() string {
	if x != nil {
		return x.ActualFee
	}
	return ""
}

func (x *OrderItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type OrderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListRequest) Reset() {
	*x = OrderListRequest{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListRequest) ProtoMessage() {}

func (x *OrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListRequest.ProtoReflect.Descriptor instead.
func (*OrderListRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{16}
}

func (x *OrderListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderItem           `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	AliPay        int64                  `protobuf:"varint,2,opt,name=AliPay,proto3" json:"AliPay,omitempty"`
	Wx            int64                  `protobuf:"varint,3,opt,name=Wx,proto3" json:"Wx,omitempty"`
	BankCard      int64                  `protobuf:"varint,4,opt,name=BankCard,proto3" json:"BankCard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListReply) Reset() {
	*x = OrderListReply{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListReply) ProtoMessage() {}

func (x *OrderListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListReply.ProtoReflect.Descriptor instead.
func (*OrderListReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{17}
}

func (x *OrderListReply) GetList() []*OrderItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *OrderListReply) GetAliPay() int64 {
	if x != nil {
		return x.AliPay
	}
	return 0
}

func (x *OrderListReply) GetWx() int64 {
	if x != nil {
		return x.Wx
	}
	return 0
}

func (x *OrderListReply) GetBankCard() int64 {
	if x != nil {
		return x.BankCard
	}
	return 0
}

type PaymentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	PayNo         string                 `protobuf:"bytes,2,opt,name=PayNo,proto3" json:"PayNo,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=Channel,proto3" json:"Channel,omitempty"`
	Amount        float32                `protobuf:"fixed32,4,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`
	PaidAt        string                 `protobuf:"bytes,7,opt,name=PaidAt,proto3" json:"PaidAt,omitempty"`
	ThirdTxId     string                 `protobuf:"bytes,8,opt,name=ThirdTxId,proto3" json:"ThirdTxId,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UserName      string                 `protobuf:"bytes,10,opt,name=UserName,proto3" json:"UserName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentItem) Reset() {
	*x = PaymentItem{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentItem) ProtoMessage() {}

func (x *PaymentItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentItem.ProtoReflect.Descriptor instead.
func (*PaymentItem) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{18}
}

func (x *PaymentItem) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *PaymentItem) GetPayNo() string {
	if x != nil {
		return x.PayNo
	}
	return ""
}

func (x *PaymentItem) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentItem) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentItem) GetPaidAt() string {
	if x != nil {
		return x.PaidAt
	}
	return ""
}

func (x *PaymentItem) GetThirdTxId() string {
	if x != nil {
		return x.ThirdTxId
	}
	return ""
}

func (x *PaymentItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentItem) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type PaymentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentListRequest) Reset() {
	*x = PaymentListRequest{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentListRequest) ProtoMessage() {}

func (x *PaymentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentListRequest.ProtoReflect.Descriptor instead.
func (*PaymentListRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{19}
}

func (x *PaymentListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PaymentListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PaymentItem         `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentListReply) Reset() {
	*x = PaymentListReply{}
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentListReply) ProtoMessage() {}

func (x *PaymentListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_payment_payment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentListReply.ProtoReflect.Descriptor instead.
func (*PaymentListReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_payment_payment_proto_rawDescGZIP(), []int{20}
}

func (x *PaymentListReply) GetList() []*PaymentItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_api_helloworld_payment_payment_proto protoreflect.FileDescriptor

const file_api_helloworld_payment_payment_proto_rawDesc = "" +
	"\n" +
	"$api/helloworld/payment/payment.proto\x12\x16api.helloworld.payment\x1a\x1cgoogle/api/annotations.proto\"\x16\n" +
	"\x14UpdatePaymentRequest\",\n" +
	"\x12UpdatePaymentReply\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\tR\x06Result\"@\n" +
	"\x1cCreatedReconciliationRequest\x12 \n" +
	"\vCreatedTime\x18\x01 \x01(\tR\vCreatedTime\"H\n" +
	"\x1aCreatedReconciliationReply\x12*\n" +
	"\x10ReconciliationId\x18\x01 \x01(\x03R\x10ReconciliationId\"\x8e\x02\n" +
	"\x12ReconciliationItem\x12\x1a\n" +
	"\bTaskName\x18\x01 \x01(\tR\bTaskName\x12*\n" +
	"\x10ReconciliationNo\x18\x02 \x01(\tR\x10ReconciliationNo\x12.\n" +
	"\x12ReconciliationDate\x18\x03 \x01(\tR\x12ReconciliationDate\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x02R\x06Amount\x12\"\n" +
	"\fActualAmount\x18\x05 \x01(\x02R\fActualAmount\x12\x1e\n" +
	"\n" +
	"Proportion\x18\x06 \x01(\tR\n" +
	"Proportion\x12$\n" +
	"\rHandlerStatus\x18\a \x01(\tR\rHandlerStatus\"Q\n" +
	"\x19ListReconciliationRequest\x12\x1a\n" +
	"\bPlayTime\x18\x01 \x01(\tR\bPlayTime\x12\x18\n" +
	"\aEndTime\x18\x02 \x01(\tR\aEndTime\"Y\n" +
	"\x17ListReconciliationReply\x12>\n" +
	"\x04list\x18\x01 \x03(\v2*.api.helloworld.payment.ReconciliationItemR\x04list\"Q\n" +
	"\x13PaymentOrderRequest\x12\x18\n" +
	"\aOrderSn\x18\x01 \x01(\tR\aOrderSn\x12 \n" +
	"\vPaymentType\x18\x02 \x01(\tR\vPaymentType\"%\n" +
	"\x11PaymentOrderReply\x12\x10\n" +
	"\x03Url\x18\x01 \x01(\tR\x03Url\"R\n" +
	"\x14MonitorCreateRequest\x12\x18\n" +
	"\aOrderNo\x18\x01 \x01(\tR\aOrderNo\x12 \n" +
	"\vMonitorType\x18\x02 \x01(\tR\vMonitorType\"$\n" +
	"\x12MonitorCreateReply\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"X\n" +
	"\x14MonitorUpdateRequest\x12\x1c\n" +
	"\tMonitorNo\x18\x01 \x01(\tR\tMonitorNo\x12\"\n" +
	"\fHandleResult\x18\x02 \x01(\tR\fHandleResult\"$\n" +
	"\x12MonitorUpdateReply\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\"&\n" +
	"\x14MonitorDeleteRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\".\n" +
	"\x12MonitorDeleteReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xdf\x02\n" +
	"\tOrderItem\x12\x18\n" +
	"\aOrderNo\x18\x01 \x01(\tR\aOrderNo\x12\x1e\n" +
	"\n" +
	"SenderName\x18\x02 \x01(\tR\n" +
	"SenderName\x12 \n" +
	"\vSenderPhone\x18\x03 \x01(\tR\vSenderPhone\x12$\n" +
	"\rSenderAddress\x18\x04 \x01(\tR\rSenderAddress\x12\"\n" +
	"\fReceiverName\x18\x05 \x01(\tR\fReceiverName\x12$\n" +
	"\rReceiverPhone\x18\x06 \x01(\tR\rReceiverPhone\x12(\n" +
	"\x0fReceiverAddress\x18\a \x01(\tR\x0fReceiverAddress\x12 \n" +
	"\vProductType\x18\b \x01(\tR\vProductType\x12\x1c\n" +
	"\tActualFee\x18\t \x01(\tR\tActualFee\x12\x1c\n" +
	"\tCreatedAt\x18\n" +
	" \x01(\tR\tCreatedAt\"*\n" +
	"\x10OrderListRequest\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"\x8b\x01\n" +
	"\x0eOrderListReply\x125\n" +
	"\x04List\x18\x01 \x03(\v2!.api.helloworld.payment.OrderItemR\x04List\x12\x16\n" +
	"\x06AliPay\x18\x02 \x01(\x03R\x06AliPay\x12\x0e\n" +
	"\x02Wx\x18\x03 \x01(\x03R\x02Wx\x12\x1a\n" +
	"\bBankCard\x18\x04 \x01(\x03R\bBankCard\"\x93\x02\n" +
	"\vPaymentItem\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId\x12\x14\n" +
	"\x05PayNo\x18\x02 \x01(\tR\x05PayNo\x12\x18\n" +
	"\aChannel\x18\x03 \x01(\tR\aChannel\x12\x16\n" +
	"\x06Amount\x18\x04 \x01(\x02R\x06Amount\x12\x1a\n" +
	"\bCurrency\x18\x05 \x01(\tR\bCurrency\x12\x16\n" +
	"\x06Status\x18\x06 \x01(\tR\x06Status\x12\x16\n" +
	"\x06PaidAt\x18\a \x01(\tR\x06PaidAt\x12\x1c\n" +
	"\tThirdTxId\x18\b \x01(\tR\tThirdTxId\x12\x1c\n" +
	"\tCreatedAt\x18\t \x01(\tR\tCreatedAt\x12\x1a\n" +
	"\bUserName\x18\n" +
	" \x01(\tR\bUserName\",\n" +
	"\x12PaymentListRequest\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\tR\x06Status\"K\n" +
	"\x10PaymentListReply\x127\n" +
	"\x04List\x18\x01 \x03(\v2#.api.helloworld.payment.PaymentItemR\x04List2\xd4\t\n" +
	"\aPayment\x12\x84\x01\n" +
	"\rUpdatePayment\x12,.api.helloworld.payment.UpdatePaymentRequest\x1a*.api.helloworld.payment.UpdatePaymentReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0epayment/update\x12\xa3\x01\n" +
	"\x15CreatedReconciliation\x124.api.helloworld.payment.CreatedReconciliationRequest\x1a2.api.helloworld.payment.CreatedReconciliationReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15reconciliation/create\x12\x95\x01\n" +
	"\x12ListReconciliation\x121.api.helloworld.payment.ListReconciliationRequest\x1a/.api.helloworld.payment.ListReconciliationReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13reconciliation/list\x12\x80\x01\n" +
	"\fPaymentOrder\x12+.api.helloworld.payment.PaymentOrderRequest\x1a).api.helloworld.payment.PaymentOrderReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\rpayment/order\x12\x84\x01\n" +
	"\rMonitorCreate\x12,.api.helloworld.payment.MonitorCreateRequest\x1a*.api.helloworld.payment.MonitorCreateReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0eMonitor/Create\x12\x84\x01\n" +
	"\rMonitorUpdate\x12,.api.helloworld.payment.MonitorUpdateRequest\x1a*.api.helloworld.payment.MonitorUpdateReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0eMonitor/Update\x12\x84\x01\n" +
	"\rMonitorDelete\x12,.api.helloworld.payment.MonitorDeleteRequest\x1a*.api.helloworld.payment.MonitorDeleteReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0eMonitor/Delete\x12q\n" +
	"\tOrderList\x12(.api.helloworld.payment.OrderListRequest\x1a&.api.helloworld.payment.OrderListReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"Order/List\x12y\n" +
	"\vPaymentList\x12*.api.helloworld.payment.PaymentListRequest\x1a(.api.helloworld.payment.PaymentListReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\fpayment/ListBI\n" +
	"\x16api.helloworld.paymentP\x01Z-ShunFengParcel/api/helloworld/payment;paymentb\x06proto3"

var (
	file_api_helloworld_payment_payment_proto_rawDescOnce sync.Once
	file_api_helloworld_payment_payment_proto_rawDescData []byte
)

func file_api_helloworld_payment_payment_proto_rawDescGZIP() []byte {
	file_api_helloworld_payment_payment_proto_rawDescOnce.Do(func() {
		file_api_helloworld_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_payment_payment_proto_rawDesc), len(file_api_helloworld_payment_payment_proto_rawDesc)))
	})
	return file_api_helloworld_payment_payment_proto_rawDescData
}

var file_api_helloworld_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_helloworld_payment_payment_proto_goTypes = []any{
	(*UpdatePaymentRequest)(nil),         // 0: api.helloworld.payment.UpdatePaymentRequest
	(*UpdatePaymentReply)(nil),           // 1: api.helloworld.payment.UpdatePaymentReply
	(*CreatedReconciliationRequest)(nil), // 2: api.helloworld.payment.CreatedReconciliationRequest
	(*CreatedReconciliationReply)(nil),   // 3: api.helloworld.payment.CreatedReconciliationReply
	(*ReconciliationItem)(nil),           // 4: api.helloworld.payment.ReconciliationItem
	(*ListReconciliationRequest)(nil),    // 5: api.helloworld.payment.ListReconciliationRequest
	(*ListReconciliationReply)(nil),      // 6: api.helloworld.payment.ListReconciliationReply
	(*PaymentOrderRequest)(nil),          // 7: api.helloworld.payment.PaymentOrderRequest
	(*PaymentOrderReply)(nil),            // 8: api.helloworld.payment.PaymentOrderReply
	(*MonitorCreateRequest)(nil),         // 9: api.helloworld.payment.MonitorCreateRequest
	(*MonitorCreateReply)(nil),           // 10: api.helloworld.payment.MonitorCreateReply
	(*MonitorUpdateRequest)(nil),         // 11: api.helloworld.payment.MonitorUpdateRequest
	(*MonitorUpdateReply)(nil),           // 12: api.helloworld.payment.MonitorUpdateReply
	(*MonitorDeleteRequest)(nil),         // 13: api.helloworld.payment.MonitorDeleteRequest
	(*MonitorDeleteReply)(nil),           // 14: api.helloworld.payment.MonitorDeleteReply
	(*OrderItem)(nil),                    // 15: api.helloworld.payment.OrderItem
	(*OrderListRequest)(nil),             // 16: api.helloworld.payment.OrderListRequest
	(*OrderListReply)(nil),               // 17: api.helloworld.payment.OrderListReply
	(*PaymentItem)(nil),                  // 18: api.helloworld.payment.PaymentItem
	(*PaymentListRequest)(nil),           // 19: api.helloworld.payment.PaymentListRequest
	(*PaymentListReply)(nil),             // 20: api.helloworld.payment.PaymentListReply
}
var file_api_helloworld_payment_payment_proto_depIdxs = []int32{
	4,  // 0: api.helloworld.payment.ListReconciliationReply.list:type_name -> api.helloworld.payment.ReconciliationItem
	15, // 1: api.helloworld.payment.OrderListReply.List:type_name -> api.helloworld.payment.OrderItem
	18, // 2: api.helloworld.payment.PaymentListReply.List:type_name -> api.helloworld.payment.PaymentItem
	0,  // 3: api.helloworld.payment.Payment.UpdatePayment:input_type -> api.helloworld.payment.UpdatePaymentRequest
	2,  // 4: api.helloworld.payment.Payment.CreatedReconciliation:input_type -> api.helloworld.payment.CreatedReconciliationRequest
	5,  // 5: api.helloworld.payment.Payment.ListReconciliation:input_type -> api.helloworld.payment.ListReconciliationRequest
	7,  // 6: api.helloworld.payment.Payment.PaymentOrder:input_type -> api.helloworld.payment.PaymentOrderRequest
	9,  // 7: api.helloworld.payment.Payment.MonitorCreate:input_type -> api.helloworld.payment.MonitorCreateRequest
	11, // 8: api.helloworld.payment.Payment.MonitorUpdate:input_type -> api.helloworld.payment.MonitorUpdateRequest
	13, // 9: api.helloworld.payment.Payment.MonitorDelete:input_type -> api.helloworld.payment.MonitorDeleteRequest
	16, // 10: api.helloworld.payment.Payment.OrderList:input_type -> api.helloworld.payment.OrderListRequest
	19, // 11: api.helloworld.payment.Payment.PaymentList:input_type -> api.helloworld.payment.PaymentListRequest
	1,  // 12: api.helloworld.payment.Payment.UpdatePayment:output_type -> api.helloworld.payment.UpdatePaymentReply
	3,  // 13: api.helloworld.payment.Payment.CreatedReconciliation:output_type -> api.helloworld.payment.CreatedReconciliationReply
	6,  // 14: api.helloworld.payment.Payment.ListReconciliation:output_type -> api.helloworld.payment.ListReconciliationReply
	8,  // 15: api.helloworld.payment.Payment.PaymentOrder:output_type -> api.helloworld.payment.PaymentOrderReply
	10, // 16: api.helloworld.payment.Payment.MonitorCreate:output_type -> api.helloworld.payment.MonitorCreateReply
	12, // 17: api.helloworld.payment.Payment.MonitorUpdate:output_type -> api.helloworld.payment.MonitorUpdateReply
	14, // 18: api.helloworld.payment.Payment.MonitorDelete:output_type -> api.helloworld.payment.MonitorDeleteReply
	17, // 19: api.helloworld.payment.Payment.OrderList:output_type -> api.helloworld.payment.OrderListReply
	20, // 20: api.helloworld.payment.Payment.PaymentList:output_type -> api.helloworld.payment.PaymentListReply
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_helloworld_payment_payment_proto_init() }
func file_api_helloworld_payment_payment_proto_init() {
	if File_api_helloworld_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_payment_payment_proto_rawDesc), len(file_api_helloworld_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_payment_payment_proto_goTypes,
		DependencyIndexes: file_api_helloworld_payment_payment_proto_depIdxs,
		MessageInfos:      file_api_helloworld_payment_payment_proto_msgTypes,
	}.Build()
	File_api_helloworld_payment_payment_proto = out.File
	file_api_helloworld_payment_payment_proto_goTypes = nil
	file_api_helloworld_payment_payment_proto_depIdxs = nil
}
