syntax = "proto3";

package api.helloworld.payment;

import "google/api/annotations.proto";

option go_package = "ShunFengParcel/api/helloworld/payment;payment";
option java_multiple_files = true;
option java_package = "api.helloworld.payment";

service Payment {
	rpc UpdatePayment (UpdatePaymentRequest) returns (UpdatePaymentReply){
    option (google.api.http) = {
      post: "payment/update"
      body: "*"
    };
  }

  rpc CreatedReconciliation (CreatedReconciliationRequest) returns (CreatedReconciliationReply){
    option (google.api.http) = {
      post: "reconciliation/create"
      body: "*"
    };
  }

  rpc ListReconciliation (ListReconciliationRequest) returns (ListReconciliationReply){
    option (google.api.http) = {
      get: "reconciliation/list"
    };
  }

  rpc PaymentOrder (PaymentOrderRequest) returns (PaymentOrderReply){
    option (google.api.http) = {
      post: "payment/order"
      body: "*"
    };
  }

  rpc MonitorCreate (MonitorCreateRequest) returns (MonitorCreateReply){
    option (google.api.http) = {
      post: "Monitor/Create"
      body: "*"
    };
  }

  rpc MonitorUpdate (MonitorUpdateRequest) returns (MonitorUpdateReply){
    option (google.api.http) = {
      post: "Monitor/Update"
      body: "*"
    };
  }

  rpc MonitorDelete (MonitorDeleteRequest) returns (MonitorDeleteReply){
    option (google.api.http) = {
      post: "Monitor/Delete"
      body: "*"
    };
  }

  rpc OrderList (OrderListRequest) returns (OrderListReply){
    option (google.api.http) = {
      get: "Order/List"
    };
  }

  rpc PaymentList (PaymentListRequest) returns (PaymentListReply){
    option (google.api.http) = {
      get: "payment/list"
    };
  }
}

message UpdatePaymentRequest {

}

message UpdatePaymentReply {
    string Result = 1;
}

message CreatedReconciliationRequest{
  string  CreatedTime = 1;
}

message CreatedReconciliationReply{
  int64 ReconciliationId = 1;
}

message ReconciliationItem{
  string  TaskName = 1;
  string  ReconciliationNo = 2;
  string  ReconciliationDate = 3;
  float   Amount = 4;
  float   ActualAmount = 5;
  string  Proportion = 6;
  string  HandlerStatus = 7;
}

message ListReconciliationRequest{
  string PlayTime = 1;
  string EndTime = 2;
}

message ListReconciliationReply{
  repeated ReconciliationItem list = 1;
}

message PaymentOrderRequest{
  string OrderSn = 1;
  string PaymentType = 2;
}

message PaymentOrderReply{
  string Url = 1;
}

message MonitorCreateRequest{
  string OrderNo = 1;
  string  MonitorType = 2;
}

message MonitorCreateReply{
  int64 Id = 1;
}

message MonitorUpdateRequest{
  string MonitorNo = 1;
  string  HandleResult = 2;
}

message MonitorUpdateReply{
  int64 Id = 1;
}

message MonitorDeleteRequest{
  int64 Id = 1;
}

message MonitorDeleteReply{
  string message = 1;
}

message OrderItem{
  string OrderNo = 1;
  string SenderName= 2;
  string SenderPhone= 3;
  string SenderAddress= 4;
  string ReceiverName= 5;
  string ReceiverPhone= 6;
  string ReceiverAddress= 7;
  string ProductType= 8;
  string ActualFee= 9;
  string CreatedAt= 10;
}

message OrderListRequest {
  string Status = 1;
}

message OrderListReply{
  repeated OrderItem List = 1;
  int64 AliPay = 2;
  int64 Wx  = 3;
  int64 BankCard =4;
}

message PaymentItem {
  int64  OrderId = 1;
  string PayNo = 2;
  string Channel = 3;
  float  Amount =4;
  string Currency =5 ;
  string Status = 6;
  string PaidAt = 7;
  string ThirdTxId = 8;
  string CreatedAt = 9;
  string UserName = 10;
}

message PaymentListRequest {
  string Status = 1;
}


message PaymentListReply {
   repeated  PaymentItem List = 1;
}
