// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: api/helloworld/payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Payment_UpdatePayment_FullMethodName         = "/api.helloworld.payment.Payment/UpdatePayment"
	Payment_CreatedReconciliation_FullMethodName = "/api.helloworld.payment.Payment/CreatedReconciliation"
	Payment_ListReconciliation_FullMethodName    = "/api.helloworld.payment.Payment/ListReconciliation"
	Payment_PaymentOrder_FullMethodName          = "/api.helloworld.payment.Payment/PaymentOrder"
	Payment_MonitorCreate_FullMethodName         = "/api.helloworld.payment.Payment/MonitorCreate"
	Payment_MonitorUpdate_FullMethodName         = "/api.helloworld.payment.Payment/MonitorUpdate"
	Payment_MonitorDelete_FullMethodName         = "/api.helloworld.payment.Payment/MonitorDelete"
	Payment_OrderList_FullMethodName             = "/api.helloworld.payment.Payment/OrderList"
	Payment_PaymentList_FullMethodName           = "/api.helloworld.payment.Payment/PaymentList"
)

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentClient interface {
	UpdatePayment(ctx context.Context, in *UpdatePaymentRequest, opts ...grpc.CallOption) (*UpdatePaymentReply, error)
	CreatedReconciliation(ctx context.Context, in *CreatedReconciliationRequest, opts ...grpc.CallOption) (*CreatedReconciliationReply, error)
	ListReconciliation(ctx context.Context, in *ListReconciliationRequest, opts ...grpc.CallOption) (*ListReconciliationReply, error)
	PaymentOrder(ctx context.Context, in *PaymentOrderRequest, opts ...grpc.CallOption) (*PaymentOrderReply, error)
	MonitorCreate(ctx context.Context, in *MonitorCreateRequest, opts ...grpc.CallOption) (*MonitorCreateReply, error)
	MonitorUpdate(ctx context.Context, in *MonitorUpdateRequest, opts ...grpc.CallOption) (*MonitorUpdateReply, error)
	MonitorDelete(ctx context.Context, in *MonitorDeleteRequest, opts ...grpc.CallOption) (*MonitorDeleteReply, error)
	OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListReply, error)
	PaymentList(ctx context.Context, in *PaymentListRequest, opts ...grpc.CallOption) (*PaymentListReply, error)
}

type paymentClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentClient(cc grpc.ClientConnInterface) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) UpdatePayment(ctx context.Context, in *UpdatePaymentRequest, opts ...grpc.CallOption) (*UpdatePaymentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePaymentReply)
	err := c.cc.Invoke(ctx, Payment_UpdatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) CreatedReconciliation(ctx context.Context, in *CreatedReconciliationRequest, opts ...grpc.CallOption) (*CreatedReconciliationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatedReconciliationReply)
	err := c.cc.Invoke(ctx, Payment_CreatedReconciliation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) ListReconciliation(ctx context.Context, in *ListReconciliationRequest, opts ...grpc.CallOption) (*ListReconciliationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReconciliationReply)
	err := c.cc.Invoke(ctx, Payment_ListReconciliation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) PaymentOrder(ctx context.Context, in *PaymentOrderRequest, opts ...grpc.CallOption) (*PaymentOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentOrderReply)
	err := c.cc.Invoke(ctx, Payment_PaymentOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) MonitorCreate(ctx context.Context, in *MonitorCreateRequest, opts ...grpc.CallOption) (*MonitorCreateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorCreateReply)
	err := c.cc.Invoke(ctx, Payment_MonitorCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) MonitorUpdate(ctx context.Context, in *MonitorUpdateRequest, opts ...grpc.CallOption) (*MonitorUpdateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorUpdateReply)
	err := c.cc.Invoke(ctx, Payment_MonitorUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) MonitorDelete(ctx context.Context, in *MonitorDeleteRequest, opts ...grpc.CallOption) (*MonitorDeleteReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonitorDeleteReply)
	err := c.cc.Invoke(ctx, Payment_MonitorDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderListReply)
	err := c.cc.Invoke(ctx, Payment_OrderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) PaymentList(ctx context.Context, in *PaymentListRequest, opts ...grpc.CallOption) (*PaymentListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentListReply)
	err := c.cc.Invoke(ctx, Payment_PaymentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
// All implementations must embed UnimplementedPaymentServer
// for forward compatibility.
type PaymentServer interface {
	UpdatePayment(context.Context, *UpdatePaymentRequest) (*UpdatePaymentReply, error)
	CreatedReconciliation(context.Context, *CreatedReconciliationRequest) (*CreatedReconciliationReply, error)
	ListReconciliation(context.Context, *ListReconciliationRequest) (*ListReconciliationReply, error)
	PaymentOrder(context.Context, *PaymentOrderRequest) (*PaymentOrderReply, error)
	MonitorCreate(context.Context, *MonitorCreateRequest) (*MonitorCreateReply, error)
	MonitorUpdate(context.Context, *MonitorUpdateRequest) (*MonitorUpdateReply, error)
	MonitorDelete(context.Context, *MonitorDeleteRequest) (*MonitorDeleteReply, error)
	OrderList(context.Context, *OrderListRequest) (*OrderListReply, error)
	PaymentList(context.Context, *PaymentListRequest) (*PaymentListReply, error)
	mustEmbedUnimplementedPaymentServer()
}

// UnimplementedPaymentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServer struct{}

func (UnimplementedPaymentServer) UpdatePayment(context.Context, *UpdatePaymentRequest) (*UpdatePaymentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePayment not implemented")
}
func (UnimplementedPaymentServer) CreatedReconciliation(context.Context, *CreatedReconciliationRequest) (*CreatedReconciliationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatedReconciliation not implemented")
}
func (UnimplementedPaymentServer) ListReconciliation(context.Context, *ListReconciliationRequest) (*ListReconciliationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReconciliation not implemented")
}
func (UnimplementedPaymentServer) PaymentOrder(context.Context, *PaymentOrderRequest) (*PaymentOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentOrder not implemented")
}
func (UnimplementedPaymentServer) MonitorCreate(context.Context, *MonitorCreateRequest) (*MonitorCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorCreate not implemented")
}
func (UnimplementedPaymentServer) MonitorUpdate(context.Context, *MonitorUpdateRequest) (*MonitorUpdateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorUpdate not implemented")
}
func (UnimplementedPaymentServer) MonitorDelete(context.Context, *MonitorDeleteRequest) (*MonitorDeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonitorDelete not implemented")
}
func (UnimplementedPaymentServer) OrderList(context.Context, *OrderListRequest) (*OrderListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderList not implemented")
}
func (UnimplementedPaymentServer) PaymentList(context.Context, *PaymentListRequest) (*PaymentListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentList not implemented")
}
func (UnimplementedPaymentServer) mustEmbedUnimplementedPaymentServer() {}
func (UnimplementedPaymentServer) testEmbeddedByValue()                 {}

// UnsafePaymentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServer will
// result in compilation errors.
type UnsafePaymentServer interface {
	mustEmbedUnimplementedPaymentServer()
}

func RegisterPaymentServer(s grpc.ServiceRegistrar, srv PaymentServer) {
	// If the following call pancis, it indicates UnimplementedPaymentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Payment_ServiceDesc, srv)
}

func _Payment_UpdatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).UpdatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_UpdatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).UpdatePayment(ctx, req.(*UpdatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_CreatedReconciliation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatedReconciliationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).CreatedReconciliation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_CreatedReconciliation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).CreatedReconciliation(ctx, req.(*CreatedReconciliationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_ListReconciliation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReconciliationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ListReconciliation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_ListReconciliation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ListReconciliation(ctx, req.(*ListReconciliationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_PaymentOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).PaymentOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_PaymentOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).PaymentOrder(ctx, req.(*PaymentOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_MonitorCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).MonitorCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_MonitorCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).MonitorCreate(ctx, req.(*MonitorCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_MonitorUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).MonitorUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_MonitorUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).MonitorUpdate(ctx, req.(*MonitorUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_MonitorDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitorDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).MonitorDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_MonitorDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).MonitorDelete(ctx, req.(*MonitorDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_OrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).OrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_OrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).OrderList(ctx, req.(*OrderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_PaymentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).PaymentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_PaymentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).PaymentList(ctx, req.(*PaymentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Payment_ServiceDesc is the grpc.ServiceDesc for Payment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.helloworld.payment.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePayment",
			Handler:    _Payment_UpdatePayment_Handler,
		},
		{
			MethodName: "CreatedReconciliation",
			Handler:    _Payment_CreatedReconciliation_Handler,
		},
		{
			MethodName: "ListReconciliation",
			Handler:    _Payment_ListReconciliation_Handler,
		},
		{
			MethodName: "PaymentOrder",
			Handler:    _Payment_PaymentOrder_Handler,
		},
		{
			MethodName: "MonitorCreate",
			Handler:    _Payment_MonitorCreate_Handler,
		},
		{
			MethodName: "MonitorUpdate",
			Handler:    _Payment_MonitorUpdate_Handler,
		},
		{
			MethodName: "MonitorDelete",
			Handler:    _Payment_MonitorDelete_Handler,
		},
		{
			MethodName: "OrderList",
			Handler:    _Payment_OrderList_Handler,
		},
		{
			MethodName: "PaymentList",
			Handler:    _Payment_PaymentList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/helloworld/payment/payment.proto",
}
