// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.11
// source: api/helloworld/v1/admin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type AdminRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRegisterReq) Reset() {
	*x = AdminRegisterReq{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegisterReq) ProtoMessage() {}

func (x *AdminRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegisterReq.ProtoReflect.Descriptor instead.
func (*AdminRegisterReq) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminRegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminRegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// The response message containing the greetings
type AdminRegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRegisterResp) Reset() {
	*x = AdminRegisterResp{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegisterResp) ProtoMessage() {}

func (x *AdminRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegisterResp.ProtoReflect.Descriptor instead.
func (*AdminRegisterResp) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminRegisterResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindAdminByUsernameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAdminByUsernameReq) Reset() {
	*x = FindAdminByUsernameReq{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAdminByUsernameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAdminByUsernameReq) ProtoMessage() {}

func (x *FindAdminByUsernameReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAdminByUsernameReq.ProtoReflect.Descriptor instead.
func (*FindAdminByUsernameReq) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *FindAdminByUsernameReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FindAdminByUsernameReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// The response message containing the greetings
type FindAdminByUsernameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAdminByUsernameResp) Reset() {
	*x = FindAdminByUsernameResp{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAdminByUsernameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAdminByUsernameResp) ProtoMessage() {}

func (x *FindAdminByUsernameResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAdminByUsernameResp.ProtoReflect.Descriptor instead.
func (*FindAdminByUsernameResp) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *FindAdminByUsernameResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateAdminPersonalReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminPersonalReq) Reset() {
	*x = UpdateAdminPersonalReq{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminPersonalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminPersonalReq) ProtoMessage() {}

func (x *UpdateAdminPersonalReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminPersonalReq.ProtoReflect.Descriptor instead.
func (*UpdateAdminPersonalReq) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAdminPersonalReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAdminPersonalReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateAdminPersonalReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateAdminPersonalReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// The response message containing the greetings
type UpdateAdminPersonalResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminPersonalResp) Reset() {
	*x = UpdateAdminPersonalResp{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminPersonalResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminPersonalResp) ProtoMessage() {}

func (x *UpdateAdminPersonalResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminPersonalResp.ProtoReflect.Descriptor instead.
func (*UpdateAdminPersonalResp) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{5}
}

type AdminStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminStatusReq) Reset() {
	*x = AdminStatusReq{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatusReq) ProtoMessage() {}

func (x *AdminStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatusReq.ProtoReflect.Descriptor instead.
func (*AdminStatusReq) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *AdminStatusReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// The response message containing the greetings
type AdminStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminStatusResp) Reset() {
	*x = AdminStatusResp{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatusResp) ProtoMessage() {}

func (x *AdminStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatusResp.ProtoReflect.Descriptor instead.
func (*AdminStatusResp) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *AdminStatusResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateAdminStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminStatusReq) Reset() {
	*x = UpdateAdminStatusReq{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminStatusReq) ProtoMessage() {}

func (x *UpdateAdminStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateAdminStatusReq) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAdminStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAdminStatusReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// The response message containing the greetings
type UpdateAdminStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminStatusResp) Reset() {
	*x = UpdateAdminStatusResp{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminStatusResp) ProtoMessage() {}

func (x *UpdateAdminStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateAdminStatusResp) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{9}
}

type SendSmsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsReq) Reset() {
	*x = SendSmsReq{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsReq) ProtoMessage() {}

func (x *SendSmsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsReq.ProtoReflect.Descriptor instead.
func (*SendSmsReq) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *SendSmsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SendSmsReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// The response message containing the greetings
type SendSmsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsResp) Reset() {
	*x = SendSmsResp{}
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsResp) ProtoMessage() {}

func (x *SendSmsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsResp.ProtoReflect.Descriptor instead.
func (*SendSmsResp) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_admin_proto_rawDescGZIP(), []int{11}
}

var File_api_helloworld_v1_admin_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/helloworld/v1/admin.proto\x12\x06stream\x1a\x1cgoogle/api/annotations.proto\"J\n" +
	"\x10AdminRegisterReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"#\n" +
	"\x11AdminRegisterResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"P\n" +
	"\x16FindAdminByUsernameReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\")\n" +
	"\x17FindAdminByUsernameResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"p\n" +
	"\x16UpdateAdminPersonalReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\x19\n" +
	"\x17UpdateAdminPersonalResp\",\n" +
	"\x0eAdminStatusReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\")\n" +
	"\x0fAdminStatusResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\">\n" +
	"\x14UpdateAdminStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\"\x17\n" +
	"\x15UpdateAdminStatusResp\"4\n" +
	"\n" +
	"SendSmsReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\"\r\n" +
	"\vSendSmsResp2\xf8\x04\n" +
	"\x05Admin\x12`\n" +
	"\rAdminRegister\x12\x18.stream.AdminRegisterReq\x1a\x19.stream.AdminRegisterResp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/admin/register\x12}\n" +
	"\x13FindAdminByUsername\x12\x1e.stream.FindAdminByUsernameReq\x1a\x1f.stream.FindAdminByUsernameResp\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/admin/findadminbyusername\x12x\n" +
	"\x13UpdateAdminPersonal\x12\x1e.stream.UpdateAdminPersonalReq\x1a\x1f.stream.UpdateAdminPersonalResp\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/admin/update/prsonal\x12X\n" +
	"\vAdminStatus\x12\x16.stream.AdminStatusReq\x1a\x17.stream.AdminStatusResp\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/admin/status\x12q\n" +
	"\x11UpdateAdminStatus\x12\x1c.stream.UpdateAdminStatusReq\x1a\x1d.stream.UpdateAdminStatusResp\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/admin/status/update\x12G\n" +
	"\aSendSms\x12\x12.stream.SendSmsReq\x1a\x13.stream.SendSmsResp\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/sendsmsBX\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z#ShunFengParcel/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_admin_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_admin_proto_rawDescData []byte
)

func file_api_helloworld_v1_admin_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_admin_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_admin_proto_rawDesc), len(file_api_helloworld_v1_admin_proto_rawDesc)))
	})
	return file_api_helloworld_v1_admin_proto_rawDescData
}

var file_api_helloworld_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_helloworld_v1_admin_proto_goTypes = []any{
	(*AdminRegisterReq)(nil),        // 0: stream.AdminRegisterReq
	(*AdminRegisterResp)(nil),       // 1: stream.AdminRegisterResp
	(*FindAdminByUsernameReq)(nil),  // 2: stream.FindAdminByUsernameReq
	(*FindAdminByUsernameResp)(nil), // 3: stream.FindAdminByUsernameResp
	(*UpdateAdminPersonalReq)(nil),  // 4: stream.UpdateAdminPersonalReq
	(*UpdateAdminPersonalResp)(nil), // 5: stream.UpdateAdminPersonalResp
	(*AdminStatusReq)(nil),          // 6: stream.AdminStatusReq
	(*AdminStatusResp)(nil),         // 7: stream.AdminStatusResp
	(*UpdateAdminStatusReq)(nil),    // 8: stream.UpdateAdminStatusReq
	(*UpdateAdminStatusResp)(nil),   // 9: stream.UpdateAdminStatusResp
	(*SendSmsReq)(nil),              // 10: stream.SendSmsReq
	(*SendSmsResp)(nil),             // 11: stream.SendSmsResp
}
var file_api_helloworld_v1_admin_proto_depIdxs = []int32{
	0,  // 0: stream.Admin.AdminRegister:input_type -> stream.AdminRegisterReq
	2,  // 1: stream.Admin.FindAdminByUsername:input_type -> stream.FindAdminByUsernameReq
	4,  // 2: stream.Admin.UpdateAdminPersonal:input_type -> stream.UpdateAdminPersonalReq
	6,  // 3: stream.Admin.AdminStatus:input_type -> stream.AdminStatusReq
	8,  // 4: stream.Admin.UpdateAdminStatus:input_type -> stream.UpdateAdminStatusReq
	10, // 5: stream.Admin.SendSms:input_type -> stream.SendSmsReq
	1,  // 6: stream.Admin.AdminRegister:output_type -> stream.AdminRegisterResp
	3,  // 7: stream.Admin.FindAdminByUsername:output_type -> stream.FindAdminByUsernameResp
	5,  // 8: stream.Admin.UpdateAdminPersonal:output_type -> stream.UpdateAdminPersonalResp
	7,  // 9: stream.Admin.AdminStatus:output_type -> stream.AdminStatusResp
	9,  // 10: stream.Admin.UpdateAdminStatus:output_type -> stream.UpdateAdminStatusResp
	11, // 11: stream.Admin.SendSms:output_type -> stream.SendSmsResp
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_admin_proto_init() }
func file_api_helloworld_v1_admin_proto_init() {
	if File_api_helloworld_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_admin_proto_rawDesc), len(file_api_helloworld_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_admin_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_admin_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_admin_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_admin_proto = out.File
	file_api_helloworld_v1_admin_proto_goTypes = nil
	file_api_helloworld_v1_admin_proto_depIdxs = nil
}
