// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: api/helloworld/v1/admin.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_AdminRegister_FullMethodName       = "/stream.Admin/AdminRegister"
	Admin_FindAdminByUsername_FullMethodName = "/stream.Admin/FindAdminByUsername"
	Admin_UpdateAdminPersonal_FullMethodName = "/stream.Admin/UpdateAdminPersonal"
	Admin_AdminStatus_FullMethodName         = "/stream.Admin/AdminStatus"
	Admin_UpdateAdminStatus_FullMethodName   = "/stream.Admin/UpdateAdminStatus"
	Admin_SendSms_FullMethodName             = "/stream.Admin/SendSms"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type AdminClient interface {
	// Sends a greeting
	AdminRegister(ctx context.Context, in *AdminRegisterReq, opts ...grpc.CallOption) (*AdminRegisterResp, error)
	FindAdminByUsername(ctx context.Context, in *FindAdminByUsernameReq, opts ...grpc.CallOption) (*FindAdminByUsernameResp, error)
	UpdateAdminPersonal(ctx context.Context, in *UpdateAdminPersonalReq, opts ...grpc.CallOption) (*UpdateAdminPersonalResp, error)
	AdminStatus(ctx context.Context, in *AdminStatusReq, opts ...grpc.CallOption) (*AdminStatusResp, error)
	UpdateAdminStatus(ctx context.Context, in *UpdateAdminStatusReq, opts ...grpc.CallOption) (*UpdateAdminStatusResp, error)
	SendSms(ctx context.Context, in *SendSmsReq, opts ...grpc.CallOption) (*SendSmsResp, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) AdminRegister(ctx context.Context, in *AdminRegisterReq, opts ...grpc.CallOption) (*AdminRegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRegisterResp)
	err := c.cc.Invoke(ctx, Admin_AdminRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) FindAdminByUsername(ctx context.Context, in *FindAdminByUsernameReq, opts ...grpc.CallOption) (*FindAdminByUsernameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindAdminByUsernameResp)
	err := c.cc.Invoke(ctx, Admin_FindAdminByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminPersonal(ctx context.Context, in *UpdateAdminPersonalReq, opts ...grpc.CallOption) (*UpdateAdminPersonalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminPersonalResp)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminPersonal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) AdminStatus(ctx context.Context, in *AdminStatusReq, opts ...grpc.CallOption) (*AdminStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminStatusResp)
	err := c.cc.Invoke(ctx, Admin_AdminStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateAdminStatus(ctx context.Context, in *UpdateAdminStatusReq, opts ...grpc.CallOption) (*UpdateAdminStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdminStatusResp)
	err := c.cc.Invoke(ctx, Admin_UpdateAdminStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SendSms(ctx context.Context, in *SendSmsReq, opts ...grpc.CallOption) (*SendSmsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendSmsResp)
	err := c.cc.Invoke(ctx, Admin_SendSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
//
// The greeting service definition.
type AdminServer interface {
	// Sends a greeting
	AdminRegister(context.Context, *AdminRegisterReq) (*AdminRegisterResp, error)
	FindAdminByUsername(context.Context, *FindAdminByUsernameReq) (*FindAdminByUsernameResp, error)
	UpdateAdminPersonal(context.Context, *UpdateAdminPersonalReq) (*UpdateAdminPersonalResp, error)
	AdminStatus(context.Context, *AdminStatusReq) (*AdminStatusResp, error)
	UpdateAdminStatus(context.Context, *UpdateAdminStatusReq) (*UpdateAdminStatusResp, error)
	SendSms(context.Context, *SendSmsReq) (*SendSmsResp, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) AdminRegister(context.Context, *AdminRegisterReq) (*AdminRegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRegister not implemented")
}
func (UnimplementedAdminServer) FindAdminByUsername(context.Context, *FindAdminByUsernameReq) (*FindAdminByUsernameResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAdminByUsername not implemented")
}
func (UnimplementedAdminServer) UpdateAdminPersonal(context.Context, *UpdateAdminPersonalReq) (*UpdateAdminPersonalResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAdminPersonal not implemented")
}
func (UnimplementedAdminServer) AdminStatus(context.Context, *AdminStatusReq) (*AdminStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminStatus not implemented")
}
func (UnimplementedAdminServer) UpdateAdminStatus(context.Context, *UpdateAdminStatusReq) (*UpdateAdminStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAdminStatus not implemented")
}
func (UnimplementedAdminServer) SendSms(context.Context, *SendSmsReq) (*SendSmsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSms not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call pancis, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_AdminRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminRegister(ctx, req.(*AdminRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_FindAdminByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAdminByUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).FindAdminByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_FindAdminByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).FindAdminByUsername(ctx, req.(*FindAdminByUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminPersonal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminPersonalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminPersonal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminPersonal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminPersonal(ctx, req.(*UpdateAdminPersonalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_AdminStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).AdminStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_AdminStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).AdminStatus(ctx, req.(*AdminStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateAdminStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdminStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateAdminStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_UpdateAdminStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateAdminStatus(ctx, req.(*UpdateAdminStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_SendSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SendSms(ctx, req.(*SendSmsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminRegister",
			Handler:    _Admin_AdminRegister_Handler,
		},
		{
			MethodName: "FindAdminByUsername",
			Handler:    _Admin_FindAdminByUsername_Handler,
		},
		{
			MethodName: "UpdateAdminPersonal",
			Handler:    _Admin_UpdateAdminPersonal_Handler,
		},
		{
			MethodName: "AdminStatus",
			Handler:    _Admin_AdminStatus_Handler,
		},
		{
			MethodName: "UpdateAdminStatus",
			Handler:    _Admin_UpdateAdminStatus_Handler,
		},
		{
			MethodName: "SendSms",
			Handler:    _Admin_SendSms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/helloworld/v1/admin.proto",
}
