// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.11
// source: helloworld/v1/greeter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGreeterGeocodeAddress = "/helloworld.v1.Greeter/GeocodeAddress"
const OperationGreeterReportCourierLocation = "/helloworld.v1.Greeter/ReportCourierLocation"

type GreeterHTTPServer interface {
	// GeocodeAddress  // 单次发货→收货距离（复用前一天算法）
	//  rpc GetTaskDistance (GetTaskDistanceRequest) returns (GetTaskDistanceReply) {
	//    option (google.api.http) = {
	//      post: "/location/v1/task_distance"
	//      body: "*"
	//    };
	//  }
	//
	// 地址解析接口，将寄件地址和收件地址转换为经纬度
	GeocodeAddress(context.Context, *GeocodeAddressRequest) (*GeocodeAddressResponse, error)
	// ReportCourierLocation 快递员 App 每 5 秒上报一次
	ReportCourierLocation(context.Context, *ReportCourierLocationRequest) (*ReportCourierLocationReply, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.POST("/location/v1/report", _Greeter_ReportCourierLocation0_HTTP_Handler(srv))
	r.POST("/location/v1/geocode", _Greeter_GeocodeAddress0_HTTP_Handler(srv))
}

func _Greeter_ReportCourierLocation0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReportCourierLocationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterReportCourierLocation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReportCourierLocation(ctx, req.(*ReportCourierLocationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReportCourierLocationReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_GeocodeAddress0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GeocodeAddressRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterGeocodeAddress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GeocodeAddress(ctx, req.(*GeocodeAddressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GeocodeAddressResponse)
		return ctx.Result(200, reply)
	}
}

type GreeterHTTPClient interface {
	// GeocodeAddress  // 单次发货→收货距离（复用前一天算法）
	//  rpc GetTaskDistance (GetTaskDistanceRequest) returns (GetTaskDistanceReply) {
	//    option (google.api.http) = {
	//      post: "/location/v1/task_distance"
	//      body: "*"
	//    };
	//  }
	//
	// 地址解析接口，将寄件地址和收件地址转换为经纬度
	GeocodeAddress(ctx context.Context, req *GeocodeAddressRequest, opts ...http.CallOption) (rsp *GeocodeAddressResponse, err error)
	// ReportCourierLocation 快递员 App 每 5 秒上报一次
	ReportCourierLocation(ctx context.Context, req *ReportCourierLocationRequest, opts ...http.CallOption) (rsp *ReportCourierLocationReply, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

// GeocodeAddress  // 单次发货→收货距离（复用前一天算法）
//  rpc GetTaskDistance (GetTaskDistanceRequest) returns (GetTaskDistanceReply) {
//    option (google.api.http) = {
//      post: "/location/v1/task_distance"
//      body: "*"
//    };
//  }
//
// 地址解析接口，将寄件地址和收件地址转换为经纬度
func (c *GreeterHTTPClientImpl) GeocodeAddress(ctx context.Context, in *GeocodeAddressRequest, opts ...http.CallOption) (*GeocodeAddressResponse, error) {
	var out GeocodeAddressResponse
	pattern := "/location/v1/geocode"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterGeocodeAddress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReportCourierLocation 快递员 App 每 5 秒上报一次
func (c *GreeterHTTPClientImpl) ReportCourierLocation(ctx context.Context, in *ReportCourierLocationRequest, opts ...http.CallOption) (*ReportCourierLocationReply, error) {
	var out ReportCourierLocationReply
	pattern := "/location/v1/report"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterReportCourierLocation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
