// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.19.4
// source: helloworld/v1/greeter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGreeterSendSms = "/helloworld.v1.Greeter/SendSms"
const OperationGreeterUserLoginSendSms = "/helloworld.v1.Greeter/UserLoginSendSms"
const OperationGreeterWxLogin = "/helloworld.v1.Greeter/WxLogin"

type GreeterHTTPServer interface {
	SendSms(context.Context, *SendSmsRequest) (*SendSmsReply, error)
	// UserLoginSendSms 手机号验证码登录
	UserLoginSendSms(context.Context, *UserLoginSendSmsRequest) (*UserLoginSendSmsReply, error)
	// WxLogin 微信小程序登录
	WxLogin(context.Context, *WxLoginRequest) (*WxLoginReply, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.POST("/user/wxlogin", _Greeter_WxLogin0_HTTP_Handler(srv))
	r.POST("/user/login", _Greeter_UserLoginSendSms0_HTTP_Handler(srv))
	r.POST("/user/sendsms", _Greeter_SendSms0_HTTP_Handler(srv))
}

func _Greeter_WxLogin0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WxLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterWxLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WxLogin(ctx, req.(*WxLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WxLoginReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_UserLoginSendSms0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UserLoginSendSmsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterUserLoginSendSms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UserLoginSendSms(ctx, req.(*UserLoginSendSmsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserLoginSendSmsReply)
		return ctx.Result(200, reply)
	}
}

func _Greeter_SendSms0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendSmsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterSendSms)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendSms(ctx, req.(*SendSmsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendSmsReply)
		return ctx.Result(200, reply)
	}
}

type GreeterHTTPClient interface {
	SendSms(ctx context.Context, req *SendSmsRequest, opts ...http.CallOption) (rsp *SendSmsReply, err error)
	// UserLoginSendSms 手机号验证码登录
	UserLoginSendSms(ctx context.Context, req *UserLoginSendSmsRequest, opts ...http.CallOption) (rsp *UserLoginSendSmsReply, err error)
	// WxLogin 微信小程序登录
	WxLogin(ctx context.Context, req *WxLoginRequest, opts ...http.CallOption) (rsp *WxLoginReply, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

func (c *GreeterHTTPClientImpl) SendSms(ctx context.Context, in *SendSmsRequest, opts ...http.CallOption) (*SendSmsReply, error) {
	var out SendSmsReply
	pattern := "/user/sendsms"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterSendSms))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UserLoginSendSms 手机号验证码登录
func (c *GreeterHTTPClientImpl) UserLoginSendSms(ctx context.Context, in *UserLoginSendSmsRequest, opts ...http.CallOption) (*UserLoginSendSmsReply, error) {
	var out UserLoginSendSmsReply
	pattern := "/user/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterUserLoginSendSms))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// WxLogin 微信小程序登录
func (c *GreeterHTTPClientImpl) WxLogin(ctx context.Context, in *WxLoginRequest, opts ...http.CallOption) (*WxLoginReply, error) {
	var out WxLoginReply
	pattern := "/user/wxlogin"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterWxLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
