// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: helloworld/v1/greeter.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Greeter_ReportCourierLocation_FullMethodName = "/helloworld.v1.Greeter/ReportCourierLocation"
	Greeter_GetCourierTrajectory_FullMethodName  = "/helloworld.v1.Greeter/GetCourierTrajectory"
	Greeter_GetTaskDistance_FullMethodName       = "/helloworld.v1.Greeter/GetTaskDistance"
	Greeter_GeocodeAddress_FullMethodName        = "/helloworld.v1.Greeter/GeocodeAddress"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type GreeterClient interface {
	// 快递员 App 每 5 秒上报一次
	ReportCourierLocation(ctx context.Context, in *ReportCourierLocationRequest, opts ...grpc.CallOption) (*ReportCourierLocationReply, error)
	// 前端 / 运营后台实时拉轨迹
	GetCourierTrajectory(ctx context.Context, in *GetCourierTrajectoryRequest, opts ...grpc.CallOption) (*GetCourierTrajectoryReply, error)
	// 单次发货→收货距离（复用前一天算法）
	GetTaskDistance(ctx context.Context, in *GetTaskDistanceRequest, opts ...grpc.CallOption) (*GetTaskDistanceReply, error)
	// 地址解析接口，将寄件地址和收件地址转换为经纬度
	GeocodeAddress(ctx context.Context, in *GeocodeAddressRequest, opts ...grpc.CallOption) (*GeocodeAddressResponse, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) ReportCourierLocation(ctx context.Context, in *ReportCourierLocationRequest, opts ...grpc.CallOption) (*ReportCourierLocationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportCourierLocationReply)
	err := c.cc.Invoke(ctx, Greeter_ReportCourierLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetCourierTrajectory(ctx context.Context, in *GetCourierTrajectoryRequest, opts ...grpc.CallOption) (*GetCourierTrajectoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourierTrajectoryReply)
	err := c.cc.Invoke(ctx, Greeter_GetCourierTrajectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetTaskDistance(ctx context.Context, in *GetTaskDistanceRequest, opts ...grpc.CallOption) (*GetTaskDistanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDistanceReply)
	err := c.cc.Invoke(ctx, Greeter_GetTaskDistance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GeocodeAddress(ctx context.Context, in *GeocodeAddressRequest, opts ...grpc.CallOption) (*GeocodeAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeocodeAddressResponse)
	err := c.cc.Invoke(ctx, Greeter_GeocodeAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility.
//
// The greeting service definition.
type GreeterServer interface {
	// 快递员 App 每 5 秒上报一次
	ReportCourierLocation(context.Context, *ReportCourierLocationRequest) (*ReportCourierLocationReply, error)
	// 前端 / 运营后台实时拉轨迹
	GetCourierTrajectory(context.Context, *GetCourierTrajectoryRequest) (*GetCourierTrajectoryReply, error)
	// 单次发货→收货距离（复用前一天算法）
	GetTaskDistance(context.Context, *GetTaskDistanceRequest) (*GetTaskDistanceReply, error)
	// 地址解析接口，将寄件地址和收件地址转换为经纬度
	GeocodeAddress(context.Context, *GeocodeAddressRequest) (*GeocodeAddressResponse, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreeterServer struct{}

func (UnimplementedGreeterServer) ReportCourierLocation(context.Context, *ReportCourierLocationRequest) (*ReportCourierLocationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportCourierLocation not implemented")
}
func (UnimplementedGreeterServer) GetCourierTrajectory(context.Context, *GetCourierTrajectoryRequest) (*GetCourierTrajectoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourierTrajectory not implemented")
}
func (UnimplementedGreeterServer) GetTaskDistance(context.Context, *GetTaskDistanceRequest) (*GetTaskDistanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskDistance not implemented")
}
func (UnimplementedGreeterServer) GeocodeAddress(context.Context, *GeocodeAddressRequest) (*GeocodeAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeocodeAddress not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}
func (UnimplementedGreeterServer) testEmbeddedByValue()                 {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	// If the following call pancis, it indicates UnimplementedGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_ReportCourierLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportCourierLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).ReportCourierLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_ReportCourierLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).ReportCourierLocation(ctx, req.(*ReportCourierLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetCourierTrajectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourierTrajectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetCourierTrajectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GetCourierTrajectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetCourierTrajectory(ctx, req.(*GetCourierTrajectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetTaskDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetTaskDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GetTaskDistance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetTaskDistance(ctx, req.(*GetTaskDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GeocodeAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GeocodeAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GeocodeAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GeocodeAddress(ctx, req.(*GeocodeAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.v1.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportCourierLocation",
			Handler:    _Greeter_ReportCourierLocation_Handler,
		},
		{
			MethodName: "GetCourierTrajectory",
			Handler:    _Greeter_GetCourierTrajectory_Handler,
		},
		{
			MethodName: "GetTaskDistance",
			Handler:    _Greeter_GetTaskDistance_Handler,
		},
		{
			MethodName: "GeocodeAddress",
			Handler:    _Greeter_GeocodeAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/v1/greeter.proto",
}
