// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: helloworld/v1/greeter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type SendSmsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsReply) Reset() {
	*x = SendSmsReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsReply) ProtoMessage() {}

func (x *SendSmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsReply.ProtoReflect.Descriptor instead.
func (*SendSmsReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmsReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendSmsReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendSmsReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type UserLoginSendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	SendSms       string                 `protobuf:"bytes,2,opt,name=SendSms,proto3" json:"SendSms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginSendSmsRequest) Reset() {
	*x = UserLoginSendSmsRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginSendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginSendSmsRequest) ProtoMessage() {}

func (x *UserLoginSendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginSendSmsRequest.ProtoReflect.Descriptor instead.
func (*UserLoginSendSmsRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginSendSmsRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserLoginSendSmsRequest) GetSendSms() string {
	if x != nil {
		return x.SendSms
	}
	return ""
}

type UserLoginSendSmsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginSendSmsReply) Reset() {
	*x = UserLoginSendSmsReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginSendSmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginSendSmsReply) ProtoMessage() {}

func (x *UserLoginSendSmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginSendSmsReply.ProtoReflect.Descriptor instead.
func (*UserLoginSendSmsReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *UserLoginSendSmsReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserLoginSendSmsReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserLoginSendSmsReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 微信小程序登录请求
type WxLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                            // 微信登录凭证
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 用户昵称
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 用户头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxLoginRequest) Reset() {
	*x = WxLoginRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxLoginRequest) ProtoMessage() {}

func (x *WxLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxLoginRequest.ProtoReflect.Descriptor instead.
func (*WxLoginRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *WxLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *WxLoginRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *WxLoginRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// 微信小程序登录响应
type WxLoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                  // 自定义登录态
	Openid        string                 `protobuf:"bytes,4,opt,name=openid,proto3" json:"openid,omitempty"`                // 用户openid
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`            // 用户昵称
	UserId        int64                  `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxLoginReply) Reset() {
	*x = WxLoginReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxLoginReply) ProtoMessage() {}

func (x *WxLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxLoginReply.ProtoReflect.Descriptor instead.
func (*WxLoginReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *WxLoginReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WxLoginReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WxLoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WxLoginReply) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *WxLoginReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *WxLoginReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_helloworld_v1_greeter_proto protoreflect.FileDescriptor

const file_helloworld_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1bhelloworld/v1/greeter.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"&\n" +
	"\x0eSendSmsRequest\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\"P\n" +
	"\fSendSmsReply\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x03R\x04Code\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\tR\x04Data\"I\n" +
	"\x17UserLoginSendSmsRequest\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x18\n" +
	"\aSendSms\x18\x02 \x01(\tR\aSendSms\"Y\n" +
	"\x15UserLoginSendSmsReply\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x03R\x04Code\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\tR\x04Data\"_\n" +
	"\x0eWxLoginRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\"\x9f\x01\n" +
	"\fWxLoginReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x16\n" +
	"\x06openid\x18\x04 \x01(\tR\x06openid\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x03R\x06userId2\xc5\x02\n" +
	"\aGreeter\x12_\n" +
	"\aWxLogin\x12\x1d.helloworld.v1.WxLoginRequest\x1a\x1b.helloworld.v1.WxLoginReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/user/wxlogin\x12x\n" +
	"\x10UserLoginSendSms\x12&.helloworld.v1.UserLoginSendSmsRequest\x1a$.helloworld.v1.UserLoginSendSmsReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/user/login\x12_\n" +
	"\aSendSms\x12\x1d.helloworld.v1.SendSmsRequest\x1a\x1b.helloworld.v1.SendSmsReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/user/sendsmsBX\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z#ShunFengParcel/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_greeter_proto_rawDescOnce sync.Once
	file_helloworld_v1_greeter_proto_rawDescData []byte
)

func file_helloworld_v1_greeter_proto_rawDescGZIP() []byte {
	file_helloworld_v1_greeter_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)))
	})
	return file_helloworld_v1_greeter_proto_rawDescData
}

var file_helloworld_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_helloworld_v1_greeter_proto_goTypes = []any{
	(*SendSmsRequest)(nil),          // 0: helloworld.v1.SendSmsRequest
	(*SendSmsReply)(nil),            // 1: helloworld.v1.SendSmsReply
	(*UserLoginSendSmsRequest)(nil), // 2: helloworld.v1.UserLoginSendSmsRequest
	(*UserLoginSendSmsReply)(nil),   // 3: helloworld.v1.UserLoginSendSmsReply
	(*WxLoginRequest)(nil),          // 4: helloworld.v1.WxLoginRequest
	(*WxLoginReply)(nil),            // 5: helloworld.v1.WxLoginReply
}
var file_helloworld_v1_greeter_proto_depIdxs = []int32{
	4, // 0: helloworld.v1.Greeter.WxLogin:input_type -> helloworld.v1.WxLoginRequest
	2, // 1: helloworld.v1.Greeter.UserLoginSendSms:input_type -> helloworld.v1.UserLoginSendSmsRequest
	0, // 2: helloworld.v1.Greeter.SendSms:input_type -> helloworld.v1.SendSmsRequest
	5, // 3: helloworld.v1.Greeter.WxLogin:output_type -> helloworld.v1.WxLoginReply
	3, // 4: helloworld.v1.Greeter.UserLoginSendSms:output_type -> helloworld.v1.UserLoginSendSmsReply
	1, // 5: helloworld.v1.Greeter.SendSms:output_type -> helloworld.v1.SendSmsReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_v1_greeter_proto_init() }
func file_helloworld_v1_greeter_proto_init() {
	if File_helloworld_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_greeter_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_greeter_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_greeter_proto_msgTypes,
	}.Build()
	File_helloworld_v1_greeter_proto = out.File
	file_helloworld_v1_greeter_proto_goTypes = nil
	file_helloworld_v1_greeter_proto_depIdxs = nil
}
