// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.11
// source: helloworld/v1/greeter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 上报 ==========
type ReportCourierLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     int64                  `protobuf:"varint,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"` // GCJ-02
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"` //  google.protobuf.Timestamp ts = 4; // 客户端时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCourierLocationRequest) Reset() {
	*x = ReportCourierLocationRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCourierLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCourierLocationRequest) ProtoMessage() {}

func (x *ReportCourierLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCourierLocationRequest.ProtoReflect.Descriptor instead.
func (*ReportCourierLocationRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *ReportCourierLocationRequest) GetCourierId() int64 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

func (x *ReportCourierLocationRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *ReportCourierLocationRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

type ReportCourierLocationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCourierLocationReply) Reset() {
	*x = ReportCourierLocationReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCourierLocationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCourierLocationReply) ProtoMessage() {}

func (x *ReportCourierLocationReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCourierLocationReply.ProtoReflect.Descriptor instead.
func (*ReportCourierLocationReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{1}
}

// ========== 轨迹 ==========
type GetCourierTrajectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     int64                  `protobuf:"varint,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	LastSeconds   int32                  `protobuf:"varint,2,opt,name=last_seconds,json=lastSeconds,proto3" json:"last_seconds,omitempty"` // 回看最近 N 秒，默认 300（5 分钟）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourierTrajectoryRequest) Reset() {
	*x = GetCourierTrajectoryRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourierTrajectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourierTrajectoryRequest) ProtoMessage() {}

func (x *GetCourierTrajectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourierTrajectoryRequest.ProtoReflect.Descriptor instead.
func (*GetCourierTrajectoryRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *GetCourierTrajectoryRequest) GetCourierId() int64 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

func (x *GetCourierTrajectoryRequest) GetLastSeconds() int32 {
	if x != nil {
		return x.LastSeconds
	}
	return 0
}

type GetCourierTrajectoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourierTrajectoryReply) Reset() {
	*x = GetCourierTrajectoryReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourierTrajectoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourierTrajectoryReply) ProtoMessage() {}

func (x *GetCourierTrajectoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourierTrajectoryReply.ProtoReflect.Descriptor instead.
func (*GetCourierTrajectoryReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourierTrajectoryReply) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lng           float64                `protobuf:"fixed64,1,opt,name=lng,proto3" json:"lng,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"` //  google.protobuf.Timestamp ts = 3;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *Point) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Point) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

// ========== 发货→收货距离 ==========
type GetTaskDistanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromLng       float64                `protobuf:"fixed64,1,opt,name=from_lng,json=fromLng,proto3" json:"from_lng,omitempty"`
	FromLat       float64                `protobuf:"fixed64,2,opt,name=from_lat,json=fromLat,proto3" json:"from_lat,omitempty"`
	ToLng         float64                `protobuf:"fixed64,3,opt,name=to_lng,json=toLng,proto3" json:"to_lng,omitempty"`
	ToLat         float64                `protobuf:"fixed64,4,opt,name=to_lat,json=toLat,proto3" json:"to_lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDistanceRequest) Reset() {
	*x = GetTaskDistanceRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDistanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDistanceRequest) ProtoMessage() {}

func (x *GetTaskDistanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDistanceRequest.ProtoReflect.Descriptor instead.
func (*GetTaskDistanceRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskDistanceRequest) GetFromLng() float64 {
	if x != nil {
		return x.FromLng
	}
	return 0
}

func (x *GetTaskDistanceRequest) GetFromLat() float64 {
	if x != nil {
		return x.FromLat
	}
	return 0
}

func (x *GetTaskDistanceRequest) GetToLng() float64 {
	if x != nil {
		return x.ToLng
	}
	return 0
}

func (x *GetTaskDistanceRequest) GetToLat() float64 {
	if x != nil {
		return x.ToLat
	}
	return 0
}

type GetTaskDistanceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      int32                  `protobuf:"varint,1,opt,name=distance,proto3" json:"distance,omitempty"` // 米
	Duration      int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"` // 秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDistanceReply) Reset() {
	*x = GetTaskDistanceReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDistanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDistanceReply) ProtoMessage() {}

func (x *GetTaskDistanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDistanceReply.ProtoReflect.Descriptor instead.
func (*GetTaskDistanceReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{6}
}

func (x *GetTaskDistanceReply) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *GetTaskDistanceReply) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// ========== 地址解析 ==========
type GeocodeAddressRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderAddress   string                 `protobuf:"bytes,1,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`       // 寄件地址
	ReceiverAddress string                 `protobuf:"bytes,2,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"` // 收件地址
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GeocodeAddressRequest) Reset() {
	*x = GeocodeAddressRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeAddressRequest) ProtoMessage() {}

func (x *GeocodeAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeAddressRequest.ProtoReflect.Descriptor instead.
func (*GeocodeAddressRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{7}
}

func (x *GeocodeAddressRequest) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *GeocodeAddressRequest) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

type GeocodeAddressResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SenderLocation   *LocationInfo          `protobuf:"bytes,1,opt,name=sender_location,json=senderLocation,proto3" json:"sender_location,omitempty"`       // 寄件地址经纬度信息
	ReceiverLocation *LocationInfo          `protobuf:"bytes,2,opt,name=receiver_location,json=receiverLocation,proto3" json:"receiver_location,omitempty"` // 收件地址经纬度信息
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GeocodeAddressResponse) Reset() {
	*x = GeocodeAddressResponse{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeAddressResponse) ProtoMessage() {}

func (x *GeocodeAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeAddressResponse.ProtoReflect.Descriptor instead.
func (*GeocodeAddressResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{8}
}

func (x *GeocodeAddressResponse) GetSenderLocation() *LocationInfo {
	if x != nil {
		return x.SenderLocation
	}
	return nil
}

func (x *GeocodeAddressResponse) GetReceiverLocation() *LocationInfo {
	if x != nil {
		return x.ReceiverLocation
	}
	return nil
}

type LocationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lng           float64                `protobuf:"fixed64,1,opt,name=lng,proto3" json:"lng,omitempty"` // 经度
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"` // 纬度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationInfo) Reset() {
	*x = LocationInfo{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationInfo) ProtoMessage() {}

func (x *LocationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationInfo.ProtoReflect.Descriptor instead.
func (*LocationInfo) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{9}
}

func (x *LocationInfo) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *LocationInfo) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

var File_helloworld_v1_greeter_proto protoreflect.FileDescriptor

const file_helloworld_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1bhelloworld/v1/greeter.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"a\n" +
	"\x1cReportCourierLocationRequest\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\x03R\tcourierId\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\"\x1c\n" +
	"\x1aReportCourierLocationReply\"_\n" +
	"\x1bGetCourierTrajectoryRequest\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\x03R\tcourierId\x12!\n" +
	"\flast_seconds\x18\x02 \x01(\x05R\vlastSeconds\"I\n" +
	"\x19GetCourierTrajectoryReply\x12,\n" +
	"\x06points\x18\x01 \x03(\v2\x14.helloworld.v1.PointR\x06points\"+\n" +
	"\x05Point\x12\x10\n" +
	"\x03lng\x18\x01 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\"|\n" +
	"\x16GetTaskDistanceRequest\x12\x19\n" +
	"\bfrom_lng\x18\x01 \x01(\x01R\afromLng\x12\x19\n" +
	"\bfrom_lat\x18\x02 \x01(\x01R\afromLat\x12\x15\n" +
	"\x06to_lng\x18\x03 \x01(\x01R\x05toLng\x12\x15\n" +
	"\x06to_lat\x18\x04 \x01(\x01R\x05toLat\"N\n" +
	"\x14GetTaskDistanceReply\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x05R\bdistance\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\"i\n" +
	"\x15GeocodeAddressRequest\x12%\n" +
	"\x0esender_address\x18\x01 \x01(\tR\rsenderAddress\x12)\n" +
	"\x10receiver_address\x18\x02 \x01(\tR\x0freceiverAddress\"\xa8\x01\n" +
	"\x16GeocodeAddressResponse\x12D\n" +
	"\x0fsender_location\x18\x01 \x01(\v2\x1b.helloworld.v1.LocationInfoR\x0esenderLocation\x12H\n" +
	"\x11receiver_location\x18\x02 \x01(\v2\x1b.helloworld.v1.LocationInfoR\x10receiverLocation\"2\n" +
	"\fLocationInfo\x12\x10\n" +
	"\x03lng\x18\x01 \x01(\x01R\x03lng\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat2\xbf\x04\n" +
	"\aGreeter\x12\x8f\x01\n" +
	"\x15ReportCourierLocation\x12+.helloworld.v1.ReportCourierLocationRequest\x1a).helloworld.v1.ReportCourierLocationReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/location/v1/report\x12\x9a\x01\n" +
	"\x14GetCourierTrajectory\x12*.helloworld.v1.GetCourierTrajectoryRequest\x1a(.helloworld.v1.GetCourierTrajectoryReply\",\x82\xd3\xe4\x93\x02&\x12$/location/v1/trajectory/{courier_id}\x12\x84\x01\n" +
	"\x0fGetTaskDistance\x12%.helloworld.v1.GetTaskDistanceRequest\x1a#.helloworld.v1.GetTaskDistanceReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/location/v1/task_distance\x12~\n" +
	"\x0eGeocodeAddress\x12$.helloworld.v1.GeocodeAddressRequest\x1a%.helloworld.v1.GeocodeAddressResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/location/v1/geocodeBX\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z#ShunFengParcel/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_greeter_proto_rawDescOnce sync.Once
	file_helloworld_v1_greeter_proto_rawDescData []byte
)

func file_helloworld_v1_greeter_proto_rawDescGZIP() []byte {
	file_helloworld_v1_greeter_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)))
	})
	return file_helloworld_v1_greeter_proto_rawDescData
}

var file_helloworld_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_helloworld_v1_greeter_proto_goTypes = []any{
	(*ReportCourierLocationRequest)(nil), // 0: helloworld.v1.ReportCourierLocationRequest
	(*ReportCourierLocationReply)(nil),   // 1: helloworld.v1.ReportCourierLocationReply
	(*GetCourierTrajectoryRequest)(nil),  // 2: helloworld.v1.GetCourierTrajectoryRequest
	(*GetCourierTrajectoryReply)(nil),    // 3: helloworld.v1.GetCourierTrajectoryReply
	(*Point)(nil),                        // 4: helloworld.v1.Point
	(*GetTaskDistanceRequest)(nil),       // 5: helloworld.v1.GetTaskDistanceRequest
	(*GetTaskDistanceReply)(nil),         // 6: helloworld.v1.GetTaskDistanceReply
	(*GeocodeAddressRequest)(nil),        // 7: helloworld.v1.GeocodeAddressRequest
	(*GeocodeAddressResponse)(nil),       // 8: helloworld.v1.GeocodeAddressResponse
	(*LocationInfo)(nil),                 // 9: helloworld.v1.LocationInfo
}
var file_helloworld_v1_greeter_proto_depIdxs = []int32{
	4, // 0: helloworld.v1.GetCourierTrajectoryReply.points:type_name -> helloworld.v1.Point
	9, // 1: helloworld.v1.GeocodeAddressResponse.sender_location:type_name -> helloworld.v1.LocationInfo
	9, // 2: helloworld.v1.GeocodeAddressResponse.receiver_location:type_name -> helloworld.v1.LocationInfo
	0, // 3: helloworld.v1.Greeter.ReportCourierLocation:input_type -> helloworld.v1.ReportCourierLocationRequest
	2, // 4: helloworld.v1.Greeter.GetCourierTrajectory:input_type -> helloworld.v1.GetCourierTrajectoryRequest
	5, // 5: helloworld.v1.Greeter.GetTaskDistance:input_type -> helloworld.v1.GetTaskDistanceRequest
	7, // 6: helloworld.v1.Greeter.GeocodeAddress:input_type -> helloworld.v1.GeocodeAddressRequest
	1, // 7: helloworld.v1.Greeter.ReportCourierLocation:output_type -> helloworld.v1.ReportCourierLocationReply
	3, // 8: helloworld.v1.Greeter.GetCourierTrajectory:output_type -> helloworld.v1.GetCourierTrajectoryReply
	6, // 9: helloworld.v1.Greeter.GetTaskDistance:output_type -> helloworld.v1.GetTaskDistanceReply
	8, // 10: helloworld.v1.Greeter.GeocodeAddress:output_type -> helloworld.v1.GeocodeAddressResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_helloworld_v1_greeter_proto_init() }
func file_helloworld_v1_greeter_proto_init() {
	if File_helloworld_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_greeter_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_greeter_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_greeter_proto_msgTypes,
	}.Build()
	File_helloworld_v1_greeter_proto = out.File
	file_helloworld_v1_greeter_proto_goTypes = nil
	file_helloworld_v1_greeter_proto_depIdxs = nil
}
