// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: helloworld/v1/kuai.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kuai_DeleteKuai_FullMethodName      = "/helloworld.v1.Kuai/DeleteKuai"
	Kuai_GetTask_FullMethodName         = "/helloworld.v1.Kuai/GetTask"
	Kuai_TaskList_FullMethodName        = "/helloworld.v1.Kuai/TaskList"
	Kuai_Login_FullMethodName           = "/helloworld.v1.Kuai/Login"
	Kuai_Register_FullMethodName        = "/helloworld.v1.Kuai/Register"
	Kuai_StuUpd_FullMethodName          = "/helloworld.v1.Kuai/StuUpd"
	Kuai_TakeTask_FullMethodName        = "/helloworld.v1.Kuai/TakeTask"
	Kuai_CreateOrder_FullMethodName     = "/helloworld.v1.Kuai/CreateOrder"
	Kuai_Performance_FullMethodName     = "/helloworld.v1.Kuai/Performance"
	Kuai_OrderList_FullMethodName       = "/helloworld.v1.Kuai/OrderList"
	Kuai_HandleException_FullMethodName = "/helloworld.v1.Kuai/HandleException"
)

// KuaiClient is the client API for Kuai service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KuaiClient interface {
	DeleteKuai(ctx context.Context, in *DeleteKuaiRequest, opts ...grpc.CallOption) (*DeleteKuaiReply, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskReply, error)
	TaskList(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListReply, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	StuUpd(ctx context.Context, in *StuUpdRequest, opts ...grpc.CallOption) (*StuUpdReply, error)
	TakeTask(ctx context.Context, in *TakeTaskRequest, opts ...grpc.CallOption) (*TakeTaskReply, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error)
	Performance(ctx context.Context, in *PerformanceRequest, opts ...grpc.CallOption) (*PerformanceReply, error)
	OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListReply, error)
	HandleException(ctx context.Context, in *HandleExceptionRequest, opts ...grpc.CallOption) (*HandleExceptionReply, error)
}

type kuaiClient struct {
	cc grpc.ClientConnInterface
}

func NewKuaiClient(cc grpc.ClientConnInterface) KuaiClient {
	return &kuaiClient{cc}
}

func (c *kuaiClient) DeleteKuai(ctx context.Context, in *DeleteKuaiRequest, opts ...grpc.CallOption) (*DeleteKuaiReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKuaiReply)
	err := c.cc.Invoke(ctx, Kuai_DeleteKuai_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuaiClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskReply)
	err := c.cc.Invoke(ctx, Kuai_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuaiClient) TaskList(ctx context.Context, in *TaskListRequest, opts ...grpc.CallOption) (*TaskListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskListReply)
	err := c.cc.Invoke(ctx, Kuai_TaskList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuaiClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, Kuai_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuaiClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, Kuai_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuaiClient) StuUpd(ctx context.Context, in *StuUpdRequest, opts ...grpc.CallOption) (*StuUpdReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StuUpdReply)
	err := c.cc.Invoke(ctx, Kuai_StuUpd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuaiClient) TakeTask(ctx context.Context, in *TakeTaskRequest, opts ...grpc.CallOption) (*TakeTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeTaskReply)
	err := c.cc.Invoke(ctx, Kuai_TakeTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuaiClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderReply)
	err := c.cc.Invoke(ctx, Kuai_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuaiClient) Performance(ctx context.Context, in *PerformanceRequest, opts ...grpc.CallOption) (*PerformanceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PerformanceReply)
	err := c.cc.Invoke(ctx, Kuai_Performance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuaiClient) OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderListReply)
	err := c.cc.Invoke(ctx, Kuai_OrderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kuaiClient) HandleException(ctx context.Context, in *HandleExceptionRequest, opts ...grpc.CallOption) (*HandleExceptionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleExceptionReply)
	err := c.cc.Invoke(ctx, Kuai_HandleException_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KuaiServer is the server API for Kuai service.
// All implementations must embed UnimplementedKuaiServer
// for forward compatibility.
type KuaiServer interface {
	DeleteKuai(context.Context, *DeleteKuaiRequest) (*DeleteKuaiReply, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskReply, error)
	TaskList(context.Context, *TaskListRequest) (*TaskListReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	StuUpd(context.Context, *StuUpdRequest) (*StuUpdReply, error)
	TakeTask(context.Context, *TakeTaskRequest) (*TakeTaskReply, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error)
	Performance(context.Context, *PerformanceRequest) (*PerformanceReply, error)
	OrderList(context.Context, *OrderListRequest) (*OrderListReply, error)
	HandleException(context.Context, *HandleExceptionRequest) (*HandleExceptionReply, error)
	mustEmbedUnimplementedKuaiServer()
}

// UnimplementedKuaiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKuaiServer struct{}

func (UnimplementedKuaiServer) DeleteKuai(context.Context, *DeleteKuaiRequest) (*DeleteKuaiReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKuai not implemented")
}
func (UnimplementedKuaiServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedKuaiServer) TaskList(context.Context, *TaskListRequest) (*TaskListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaskList not implemented")
}
func (UnimplementedKuaiServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedKuaiServer) Register(context.Context, *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedKuaiServer) StuUpd(context.Context, *StuUpdRequest) (*StuUpdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StuUpd not implemented")
}
func (UnimplementedKuaiServer) TakeTask(context.Context, *TakeTaskRequest) (*TakeTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeTask not implemented")
}
func (UnimplementedKuaiServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedKuaiServer) Performance(context.Context, *PerformanceRequest) (*PerformanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Performance not implemented")
}
func (UnimplementedKuaiServer) OrderList(context.Context, *OrderListRequest) (*OrderListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderList not implemented")
}
func (UnimplementedKuaiServer) HandleException(context.Context, *HandleExceptionRequest) (*HandleExceptionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleException not implemented")
}
func (UnimplementedKuaiServer) mustEmbedUnimplementedKuaiServer() {}
func (UnimplementedKuaiServer) testEmbeddedByValue()              {}

// UnsafeKuaiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KuaiServer will
// result in compilation errors.
type UnsafeKuaiServer interface {
	mustEmbedUnimplementedKuaiServer()
}

func RegisterKuaiServer(s grpc.ServiceRegistrar, srv KuaiServer) {
	// If the following call pancis, it indicates UnimplementedKuaiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kuai_ServiceDesc, srv)
}

func _Kuai_DeleteKuai_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKuaiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).DeleteKuai(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_DeleteKuai_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).DeleteKuai(ctx, req.(*DeleteKuaiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuai_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuai_TaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).TaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_TaskList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).TaskList(ctx, req.(*TaskListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuai_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuai_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuai_StuUpd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StuUpdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).StuUpd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_StuUpd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).StuUpd(ctx, req.(*StuUpdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuai_TakeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).TakeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_TakeTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).TakeTask(ctx, req.(*TakeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuai_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuai_Performance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).Performance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_Performance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).Performance(ctx, req.(*PerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuai_OrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).OrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_OrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).OrderList(ctx, req.(*OrderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kuai_HandleException_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleExceptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KuaiServer).HandleException(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kuai_HandleException_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KuaiServer).HandleException(ctx, req.(*HandleExceptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Kuai_ServiceDesc is the grpc.ServiceDesc for Kuai service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kuai_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.v1.Kuai",
	HandlerType: (*KuaiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteKuai",
			Handler:    _Kuai_DeleteKuai_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Kuai_GetTask_Handler,
		},
		{
			MethodName: "TaskList",
			Handler:    _Kuai_TaskList_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Kuai_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Kuai_Register_Handler,
		},
		{
			MethodName: "StuUpd",
			Handler:    _Kuai_StuUpd_Handler,
		},
		{
			MethodName: "TakeTask",
			Handler:    _Kuai_TakeTask_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Kuai_CreateOrder_Handler,
		},
		{
			MethodName: "Performance",
			Handler:    _Kuai_Performance_Handler,
		},
		{
			MethodName: "OrderList",
			Handler:    _Kuai_OrderList_Handler,
		},
		{
			MethodName: "HandleException",
			Handler:    _Kuai_HandleException_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/v1/kuai.proto",
}
