// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.11
// source: helloworld/v1/kuai.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 枚举定义（示例）protobuf 枚举是“数字”，数据库枚举是“字符串”
type ServiceType int32

const (
	ServiceType_DELIVERY_OPTION_SAME_DAY ServiceType = 0
	ServiceType_DELIVERY_OPTION_NEXT_DAY ServiceType = 1
	ServiceType_DELIVERY_OPTION_STANDARD ServiceType = 2
	ServiceType_DELIVERY_OPTION_ECONOMY  ServiceType = 3
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "DELIVERY_OPTION_SAME_DAY",
		1: "DELIVERY_OPTION_NEXT_DAY",
		2: "DELIVERY_OPTION_STANDARD",
		3: "DELIVERY_OPTION_ECONOMY",
	}
	ServiceType_value = map[string]int32{
		"DELIVERY_OPTION_SAME_DAY": 0,
		"DELIVERY_OPTION_NEXT_DAY": 1,
		"DELIVERY_OPTION_STANDARD": 2,
		"DELIVERY_OPTION_ECONOMY":  3,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_v1_kuai_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_helloworld_v1_kuai_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED  PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_SENDER_PAY   PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_RECEIVER_PAY PaymentMethod = 4
	PaymentMethod_PAYMENT_METHOD_MONTHLY      PaymentMethod = 5
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		3: "PAYMENT_METHOD_SENDER_PAY",
		4: "PAYMENT_METHOD_RECEIVER_PAY",
		5: "PAYMENT_METHOD_MONTHLY",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":  0,
		"PAYMENT_METHOD_SENDER_PAY":   3,
		"PAYMENT_METHOD_RECEIVER_PAY": 4,
		"PAYMENT_METHOD_MONTHLY":      5,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_v1_kuai_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_helloworld_v1_kuai_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{1}
}

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1 // 待支付
	PaymentStatus_PAYMENT_STATUS_PAID        PaymentStatus = 2 // 已支付
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3 // 支付失败
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 4 // 已退款
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PAID",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PAID":        2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_REFUNDED":    4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_v1_kuai_proto_enumTypes[2].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_helloworld_v1_kuai_proto_enumTypes[2]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{2}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING          OrderStatus = 1 // 待接单
	OrderStatus_ORDER_STATUS_ACCEPTED         OrderStatus = 2 // 已接单
	OrderStatus_ORDER_STATUS_PICKED_UP        OrderStatus = 3 // 已取件
	OrderStatus_ORDER_STATUS_IN_TRANSIT       OrderStatus = 4 // 运输中
	OrderStatus_ORDER_STATUS_OUT_FOR_DELIVERY OrderStatus = 5 // 派送中
	OrderStatus_ORDER_STATUS_DELIVERED        OrderStatus = 6 // 已签收
	OrderStatus_ORDER_STATUS_CANCELLED        OrderStatus = 7 // 已取消
	OrderStatus_ORDER_STATUS_EXCEPTION        OrderStatus = 8 // 异常
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_ACCEPTED",
		3: "ORDER_STATUS_PICKED_UP",
		4: "ORDER_STATUS_IN_TRANSIT",
		5: "ORDER_STATUS_OUT_FOR_DELIVERY",
		6: "ORDER_STATUS_DELIVERED",
		7: "ORDER_STATUS_CANCELLED",
		8: "ORDER_STATUS_EXCEPTION",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_PENDING":          1,
		"ORDER_STATUS_ACCEPTED":         2,
		"ORDER_STATUS_PICKED_UP":        3,
		"ORDER_STATUS_IN_TRANSIT":       4,
		"ORDER_STATUS_OUT_FOR_DELIVERY": 5,
		"ORDER_STATUS_DELIVERED":        6,
		"ORDER_STATUS_CANCELLED":        7,
		"ORDER_STATUS_EXCEPTION":        8,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_v1_kuai_proto_enumTypes[3].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_helloworld_v1_kuai_proto_enumTypes[3]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{3}
}

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED TaskType = 0
	TaskType_Pickup                TaskType = 1 // 揽件
	TaskType_Delivery              TaskType = 2 // 派件
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "Pickup",
		2: "Delivery",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED": 0,
		"Pickup":                1,
		"Delivery":              2,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_v1_kuai_proto_enumTypes[4].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_helloworld_v1_kuai_proto_enumTypes[4]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{4}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0 // 未指定
	TaskStatus_Pending                 TaskStatus = 1 // 待处理
	TaskStatus_Accepted                TaskStatus = 2 // 已接单
	TaskStatus_Completed               TaskStatus = 3 // 已完成
	TaskStatus_Cancelled               TaskStatus = 4 // 已取消
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "Pending",
		2: "Accepted",
		3: "Completed",
		4: "Cancelled",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"Pending":                 1,
		"Accepted":                2,
		"Completed":               3,
		"Cancelled":               4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_v1_kuai_proto_enumTypes[5].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_helloworld_v1_kuai_proto_enumTypes[5]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{5}
}

// 异常类型枚举
type ExceptionType int32

const (
	ExceptionType_EXCEPTION_TYPE_UNSPECIFIED ExceptionType = 0
	ExceptionType_USER_CANCEL                ExceptionType = 1 // 用户取消订单
	ExceptionType_COURIER_CANCEL             ExceptionType = 2 // 快递员取消订单
	ExceptionType_DELIVERY_FAILED            ExceptionType = 3 // 派送失败
	ExceptionType_PICKUP_FAILED              ExceptionType = 4 // 取件失败
	ExceptionType_ADDRESS_ERROR              ExceptionType = 5 // 地址错误
	ExceptionType_CONTACT_FAILED             ExceptionType = 6 // 联系不上收件人
)

// Enum value maps for ExceptionType.
var (
	ExceptionType_name = map[int32]string{
		0: "EXCEPTION_TYPE_UNSPECIFIED",
		1: "USER_CANCEL",
		2: "COURIER_CANCEL",
		3: "DELIVERY_FAILED",
		4: "PICKUP_FAILED",
		5: "ADDRESS_ERROR",
		6: "CONTACT_FAILED",
	}
	ExceptionType_value = map[string]int32{
		"EXCEPTION_TYPE_UNSPECIFIED": 0,
		"USER_CANCEL":                1,
		"COURIER_CANCEL":             2,
		"DELIVERY_FAILED":            3,
		"PICKUP_FAILED":              4,
		"ADDRESS_ERROR":              5,
		"CONTACT_FAILED":             6,
	}
)

func (x ExceptionType) Enum() *ExceptionType {
	p := new(ExceptionType)
	*p = x
	return p
}

func (x ExceptionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExceptionType) Descriptor() protoreflect.EnumDescriptor {
	return file_helloworld_v1_kuai_proto_enumTypes[6].Descriptor()
}

func (ExceptionType) Type() protoreflect.EnumType {
	return &file_helloworld_v1_kuai_proto_enumTypes[6]
}

func (x ExceptionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExceptionType.Descriptor instead.
func (ExceptionType) EnumDescriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{6}
}

type PerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopN          int32                  `protobuf:"varint,1,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"` // 要前几名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceRequest) Reset() {
	*x = PerformanceRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceRequest) ProtoMessage() {}

func (x *PerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceRequest.ProtoReflect.Descriptor instead.
func (*PerformanceRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{0}
}

func (x *PerformanceRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

type PerformanceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankList      []*CourierRank         `protobuf:"bytes,1,rep,name=rank_list,json=rankList,proto3" json:"rank_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformanceReply) Reset() {
	*x = PerformanceReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceReply) ProtoMessage() {}

func (x *PerformanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceReply.ProtoReflect.Descriptor instead.
func (*PerformanceReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{1}
}

func (x *PerformanceReply) GetRankList() []*CourierRank {
	if x != nil {
		return x.RankList
	}
	return nil
}

type CourierRank struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Rank             int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	CourierId        int64                  `protobuf:"varint,2,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	CourierName      string                 `protobuf:"bytes,3,opt,name=courier_name,json=courierName,proto3" json:"courier_name,omitempty"`
	PerformanceScore float64                `protobuf:"fixed64,4,opt,name=performance_score,json=performanceScore,proto3" json:"performance_score,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CourierRank) Reset() {
	*x = CourierRank{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourierRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourierRank) ProtoMessage() {}

func (x *CourierRank) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourierRank.ProtoReflect.Descriptor instead.
func (*CourierRank) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{2}
}

func (x *CourierRank) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CourierRank) GetCourierId() int64 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

func (x *CourierRank) GetCourierName() string {
	if x != nil {
		return x.CourierName
	}
	return ""
}

func (x *CourierRank) GetPerformanceScore() float64 {
	if x != nil {
		return x.PerformanceScore
	}
	return 0
}

type CreateOrderRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                        // 用户ID
	SenderName           string                 `protobuf:"bytes,6,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`                                             // 寄件人
	SenderPhone          string                 `protobuf:"bytes,7,opt,name=sender_phone,json=senderPhone,proto3" json:"sender_phone,omitempty"`                                          // 寄件电话
	SenderAddress        string                 `protobuf:"bytes,8,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`                                    // 寄件地址（JSON 字符串）
	ReceiverName         string                 `protobuf:"bytes,9,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`                                       // 收件人
	ReceiverPhone        string                 `protobuf:"bytes,10,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`                                   // 收件电话
	ReceiverAddress      string                 `protobuf:"bytes,11,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`                             // 收件地址（JSON 字符串）
	ServiceType          ServiceType            `protobuf:"varint,12,opt,name=service_type,json=serviceType,proto3,enum=helloworld.v1.ServiceType" json:"service_type,omitempty"`         // 服务类型枚举
	ProductType          string                 `protobuf:"bytes,13,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`                                         // 物品类型
	IsInsured            int32                  `protobuf:"varint,14,opt,name=is_insured,json=isInsured,proto3" json:"is_insured,omitempty"`                                              // 是否保价
	InsuredValue         float64                `protobuf:"fixed64,15,opt,name=insured_value,json=insuredValue,proto3" json:"insured_value,omitempty"`                                    // 保价金额
	EstimatedWeight      float64                `protobuf:"fixed64,16,opt,name=estimated_weight,json=estimatedWeight,proto3" json:"estimated_weight,omitempty"`                           // 预估重量kg
	ActualWeight         float64                `protobuf:"fixed64,17,opt,name=actual_weight,json=actualWeight,proto3" json:"actual_weight,omitempty"`                                    // 实际重量kg
	VolumeWeight         float64                `protobuf:"fixed64,18,opt,name=volume_weight,json=volumeWeight,proto3" json:"volume_weight,omitempty"`                                    // 体积重量kg
	EstimatedFee         float64                `protobuf:"fixed64,20,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"`                                    // 预估费用
	ActualFee            float64                `protobuf:"fixed64,21,opt,name=actual_fee,json=actualFee,proto3" json:"actual_fee,omitempty"`                                             // 实际费用
	PaymentMethod        PaymentMethod          `protobuf:"varint,22,opt,name=payment_method,json=paymentMethod,proto3,enum=helloworld.v1.PaymentMethod" json:"payment_method,omitempty"` // 支付方式枚举
	PaymentStatus        PaymentStatus          `protobuf:"varint,23,opt,name=payment_status,json=paymentStatus,proto3,enum=helloworld.v1.PaymentStatus" json:"payment_status,omitempty"` // 支付状态枚举
	ExpectedPickupTime   int64                  `protobuf:"varint,24,opt,name=expected_pickup_time,json=expectedPickupTime,proto3" json:"expected_pickup_time,omitempty"`                 // 期望上门时间（Unix秒）
	ActualPickupTime     int64                  `protobuf:"varint,25,opt,name=actual_pickup_time,json=actualPickupTime,proto3" json:"actual_pickup_time,omitempty"`                       // 实际上门时间（Unix秒）
	ExpectedDeliveryTime int64                  `protobuf:"varint,26,opt,name=expected_delivery_time,json=expectedDeliveryTime,proto3" json:"expected_delivery_time,omitempty"`           // 期望送达时间（Unix秒）
	ActualDeliveryTime   int64                  `protobuf:"varint,27,opt,name=actual_delivery_time,json=actualDeliveryTime,proto3" json:"actual_delivery_time,omitempty"`                 // 实际送达时间（Unix秒）
	OrderStatus          OrderStatus            `protobuf:"varint,28,opt,name=order_status,json=orderStatus,proto3,enum=helloworld.v1.OrderStatus" json:"order_status,omitempty"`         // 订单状态枚举
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *CreateOrderRequest) GetSenderPhone() string {
	if x != nil {
		return x.SenderPhone
	}
	return ""
}

func (x *CreateOrderRequest) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *CreateOrderRequest) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *CreateOrderRequest) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *CreateOrderRequest) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_DELIVERY_OPTION_SAME_DAY
}

func (x *CreateOrderRequest) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *CreateOrderRequest) GetIsInsured() int32 {
	if x != nil {
		return x.IsInsured
	}
	return 0
}

func (x *CreateOrderRequest) GetInsuredValue() float64 {
	if x != nil {
		return x.InsuredValue
	}
	return 0
}

func (x *CreateOrderRequest) GetEstimatedWeight() float64 {
	if x != nil {
		return x.EstimatedWeight
	}
	return 0
}

func (x *CreateOrderRequest) GetActualWeight() float64 {
	if x != nil {
		return x.ActualWeight
	}
	return 0
}

func (x *CreateOrderRequest) GetVolumeWeight() float64 {
	if x != nil {
		return x.VolumeWeight
	}
	return 0
}

func (x *CreateOrderRequest) GetEstimatedFee() float64 {
	if x != nil {
		return x.EstimatedFee
	}
	return 0
}

func (x *CreateOrderRequest) GetActualFee() float64 {
	if x != nil {
		return x.ActualFee
	}
	return 0
}

func (x *CreateOrderRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *CreateOrderRequest) GetPaymentStatus() PaymentStatus {
	if x != nil {
		return x.PaymentStatus
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *CreateOrderRequest) GetExpectedPickupTime() int64 {
	if x != nil {
		return x.ExpectedPickupTime
	}
	return 0
}

func (x *CreateOrderRequest) GetActualPickupTime() int64 {
	if x != nil {
		return x.ActualPickupTime
	}
	return 0
}

func (x *CreateOrderRequest) GetExpectedDeliveryTime() int64 {
	if x != nil {
		return x.ExpectedDeliveryTime
	}
	return 0
}

func (x *CreateOrderRequest) GetActualDeliveryTime() int64 {
	if x != nil {
		return x.ActualDeliveryTime
	}
	return 0
}

func (x *CreateOrderRequest) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

type CreateOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReply) Reset() {
	*x = CreateOrderReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReply) ProtoMessage() {}

func (x *CreateOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReply.ProtoReflect.Descriptor instead.
func (*CreateOrderReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderReply) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type TakeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourierId     int64                  `protobuf:"varint,1,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeTaskRequest) Reset() {
	*x = TakeTaskRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeTaskRequest) ProtoMessage() {}

func (x *TakeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeTaskRequest.ProtoReflect.Descriptor instead.
func (*TakeTaskRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{5}
}

func (x *TakeTaskRequest) GetCourierId() int64 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

type TakeTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // 抢到的任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeTaskReply) Reset() {
	*x = TakeTaskReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeTaskReply) ProtoMessage() {}

func (x *TakeTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeTaskReply.ProtoReflect.Descriptor instead.
func (*TakeTaskReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{6}
}

func (x *TakeTaskReply) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourierId     int64                  `protobuf:"varint,2,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	CourierName   string                 `protobuf:"bytes,3,opt,name=courier_name,json=courierName,proto3" json:"courier_name,omitempty"`
	TaskType      TaskType               `protobuf:"varint,4,opt,name=task_type,json=taskType,proto3,enum=helloworld.v1.TaskType" json:"task_type,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"` // 优先级 P0最高(超时订单) P1高(预约即将到期) P2中(已接单) P3低(新订单)
	TaskStatus    TaskStatus             `protobuf:"varint,6,opt,name=task_status,json=taskStatus,proto3,enum=helloworld.v1.TaskStatus" json:"task_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReply) Reset() {
	*x = GetTaskReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReply) ProtoMessage() {}

func (x *GetTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReply.ProtoReflect.Descriptor instead.
func (*GetTaskReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTaskReply) GetCourierId() int64 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

func (x *GetTaskReply) GetCourierName() string {
	if x != nil {
		return x.CourierName
	}
	return ""
}

func (x *GetTaskReply) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *GetTaskReply) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *GetTaskReply) GetTaskStatus() TaskStatus {
	if x != nil {
		return x.TaskStatus
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

type StuUpdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Phone         int64                  `protobuf:"varint,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StuUpdRequest) Reset() {
	*x = StuUpdRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StuUpdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StuUpdRequest) ProtoMessage() {}

func (x *StuUpdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StuUpdRequest.ProtoReflect.Descriptor instead.
func (*StuUpdRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{9}
}

func (x *StuUpdRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StuUpdRequest) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

type StuUpdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StuUpdReply) Reset() {
	*x = StuUpdReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StuUpdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StuUpdReply) ProtoMessage() {}

func (x *StuUpdReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StuUpdReply.ProtoReflect.Descriptor instead.
func (*StuUpdReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{10}
}

func (x *StuUpdReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{13}
}

func (x *LoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{14}
}

func (x *LoginReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TaskListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskListRequest) Reset() {
	*x = TaskListRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListRequest) ProtoMessage() {}

func (x *TaskListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListRequest.ProtoReflect.Descriptor instead.
func (*TaskListRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{15}
}

type TaskListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskListReply) Reset() {
	*x = TaskListReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskListReply) ProtoMessage() {}

func (x *TaskListReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskListReply.ProtoReflect.Descriptor instead.
func (*TaskListReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{16}
}

func (x *TaskListReply) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *TaskListReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Task struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 任务ID
	CourierId       int64                  `protobuf:"varint,2,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	CourierName     string                 `protobuf:"bytes,3,opt,name=courier_name,json=courierName,proto3" json:"courier_name,omitempty"`                     // 新增
	TaskType        TaskType               `protobuf:"varint,4,opt,name=task_type,json=taskType,proto3,enum=helloworld.v1.TaskType" json:"task_type,omitempty"` // 任务类型
	Priority        int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                                             // 优先级 P0最高(超时订单) P1高(预约即将到期) P2中(已接单) P3低(新订单)
	TaskStatus      TaskStatus             `protobuf:"varint,6,opt,name=task_status,json=taskStatus,proto3,enum=helloworld.v1.TaskStatus" json:"task_status,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                   // 创建时间
	SenderAddress   string                 `protobuf:"bytes,8,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`       // 寄件地址
	ReceiverAddress string                 `protobuf:"bytes,9,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"` // 收件地址
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{17}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetCourierId() int64 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

func (x *Task) GetCourierName() string {
	if x != nil {
		return x.CourierName
	}
	return ""
}

func (x *Task) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetTaskStatus() TaskStatus {
	if x != nil {
		return x.TaskStatus
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Task) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *Task) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

type DeleteKuaiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKuaiRequest) Reset() {
	*x = DeleteKuaiRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKuaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKuaiRequest) ProtoMessage() {}

func (x *DeleteKuaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKuaiRequest.ProtoReflect.Descriptor instead.
func (*DeleteKuaiRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{18}
}

type DeleteKuaiReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKuaiReply) Reset() {
	*x = DeleteKuaiReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKuaiReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKuaiReply) ProtoMessage() {}

func (x *DeleteKuaiReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKuaiReply.ProtoReflect.Descriptor instead.
func (*DeleteKuaiReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{19}
}

type GetKuaiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKuaiRequest) Reset() {
	*x = GetKuaiRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKuaiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKuaiRequest) ProtoMessage() {}

func (x *GetKuaiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKuaiRequest.ProtoReflect.Descriptor instead.
func (*GetKuaiRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{20}
}

type GetKuaiReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKuaiReply) Reset() {
	*x = GetKuaiReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKuaiReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKuaiReply) ProtoMessage() {}

func (x *GetKuaiReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKuaiReply.ProtoReflect.Descriptor instead.
func (*GetKuaiReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{21}
}

// 订单列表
type OrderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListRequest) Reset() {
	*x = OrderListRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListRequest) ProtoMessage() {}

func (x *OrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListRequest.ProtoReflect.Descriptor instead.
func (*OrderListRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{22}
}

type OrderItem struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNo              string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	SenderName           string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	ReceiverName         string                 `protobuf:"bytes,4,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ServiceType          string                 `protobuf:"bytes,5,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	OrderStatus          string                 `protobuf:"bytes,6,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserId               int64                  `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourierId            int64                  `protobuf:"varint,9,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`
	SenderPhone          string                 `protobuf:"bytes,10,opt,name=sender_phone,json=senderPhone,proto3" json:"sender_phone,omitempty"`
	SenderAddress        string                 `protobuf:"bytes,11,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	ReceiverPhone        string                 `protobuf:"bytes,12,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverAddress      string                 `protobuf:"bytes,13,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	ProductType          string                 `protobuf:"bytes,14,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	IsInsured            int32                  `protobuf:"varint,15,opt,name=is_insured,json=isInsured,proto3" json:"is_insured,omitempty"`
	InsuredValue         float64                `protobuf:"fixed64,16,opt,name=insured_value,json=insuredValue,proto3" json:"insured_value,omitempty"`
	EstimatedWeight      float64                `protobuf:"fixed64,17,opt,name=estimated_weight,json=estimatedWeight,proto3" json:"estimated_weight,omitempty"`
	ActualWeight         float64                `protobuf:"fixed64,18,opt,name=actual_weight,json=actualWeight,proto3" json:"actual_weight,omitempty"`
	VolumeWeight         float64                `protobuf:"fixed64,19,opt,name=volume_weight,json=volumeWeight,proto3" json:"volume_weight,omitempty"`
	EstimatedFee         float64                `protobuf:"fixed64,20,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"`
	ActualFee            float64                `protobuf:"fixed64,21,opt,name=actual_fee,json=actualFee,proto3" json:"actual_fee,omitempty"`
	PaymentMethod        string                 `protobuf:"bytes,22,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PaymentStatus        string                 `protobuf:"bytes,23,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	ExpectedPickupTime   int64                  `protobuf:"varint,24,opt,name=expected_pickup_time,json=expectedPickupTime,proto3" json:"expected_pickup_time,omitempty"`
	ActualPickupTime     int64                  `protobuf:"varint,25,opt,name=actual_pickup_time,json=actualPickupTime,proto3" json:"actual_pickup_time,omitempty"`
	ExpectedDeliveryTime int64                  `protobuf:"varint,26,opt,name=expected_delivery_time,json=expectedDeliveryTime,proto3" json:"expected_delivery_time,omitempty"`
	ActualDeliveryTime   int64                  `protobuf:"varint,27,opt,name=actual_delivery_time,json=actualDeliveryTime,proto3" json:"actual_delivery_time,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,28,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            string                 `protobuf:"bytes,29,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{23}
}

func (x *OrderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderItem) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *OrderItem) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *OrderItem) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *OrderItem) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *OrderItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderItem) GetCourierId() int64 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

func (x *OrderItem) GetSenderPhone() string {
	if x != nil {
		return x.SenderPhone
	}
	return ""
}

func (x *OrderItem) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *OrderItem) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *OrderItem) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *OrderItem) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *OrderItem) GetIsInsured() int32 {
	if x != nil {
		return x.IsInsured
	}
	return 0
}

func (x *OrderItem) GetInsuredValue() float64 {
	if x != nil {
		return x.InsuredValue
	}
	return 0
}

func (x *OrderItem) GetEstimatedWeight() float64 {
	if x != nil {
		return x.EstimatedWeight
	}
	return 0
}

func (x *OrderItem) GetActualWeight() float64 {
	if x != nil {
		return x.ActualWeight
	}
	return 0
}

func (x *OrderItem) GetVolumeWeight() float64 {
	if x != nil {
		return x.VolumeWeight
	}
	return 0
}

func (x *OrderItem) GetEstimatedFee() float64 {
	if x != nil {
		return x.EstimatedFee
	}
	return 0
}

func (x *OrderItem) GetActualFee() float64 {
	if x != nil {
		return x.ActualFee
	}
	return 0
}

func (x *OrderItem) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderItem) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *OrderItem) GetExpectedPickupTime() int64 {
	if x != nil {
		return x.ExpectedPickupTime
	}
	return 0
}

func (x *OrderItem) GetActualPickupTime() int64 {
	if x != nil {
		return x.ActualPickupTime
	}
	return 0
}

func (x *OrderItem) GetExpectedDeliveryTime() int64 {
	if x != nil {
		return x.ExpectedDeliveryTime
	}
	return 0
}

func (x *OrderItem) GetActualDeliveryTime() int64 {
	if x != nil {
		return x.ActualDeliveryTime
	}
	return 0
}

func (x *OrderItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OrderItem) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type OrderListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OrderItem           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListReply) Reset() {
	*x = OrderListReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListReply) ProtoMessage() {}

func (x *OrderListReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListReply.ProtoReflect.Descriptor instead.
func (*OrderListReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{24}
}

func (x *OrderListReply) GetList() []*OrderItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 异常处理请求
type HandleExceptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                                                    // 订单ID`
	ExceptionType ExceptionType          `protobuf:"varint,2,opt,name=exception_type,json=exceptionType,proto3,enum=helloworld.v1.ExceptionType" json:"exception_type,omitempty"` // 异常类型
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                                                      // 异常原因
	CourierId     int64                  `protobuf:"varint,4,opt,name=courier_id,json=courierId,proto3" json:"courier_id,omitempty"`                                              // 快递员ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleExceptionRequest) Reset() {
	*x = HandleExceptionRequest{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleExceptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleExceptionRequest) ProtoMessage() {}

func (x *HandleExceptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleExceptionRequest.ProtoReflect.Descriptor instead.
func (*HandleExceptionRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{25}
}

func (x *HandleExceptionRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *HandleExceptionRequest) GetExceptionType() ExceptionType {
	if x != nil {
		return x.ExceptionType
	}
	return ExceptionType_EXCEPTION_TYPE_UNSPECIFIED
}

func (x *HandleExceptionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HandleExceptionRequest) GetCourierId() int64 {
	if x != nil {
		return x.CourierId
	}
	return 0
}

// 异常处理响应
type HandleExceptionReply struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                     // 处理是否成功
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                                      // 返回消息
	NewStatus           OrderStatus            `protobuf:"varint,3,opt,name=new_status,json=newStatus,proto3,enum=helloworld.v1.OrderStatus" json:"new_status,omitempty"` // 新的订单状态
	RequiresNegotiation bool                   `protobuf:"varint,4,opt,name=requires_negotiation,json=requiresNegotiation,proto3" json:"requires_negotiation,omitempty"`  // 是否需要协商空跑费
	SuggestedFee        float64                `protobuf:"fixed64,5,opt,name=suggested_fee,json=suggestedFee,proto3" json:"suggested_fee,omitempty"`                      // 建议的空跑费金额(0-10元)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HandleExceptionReply) Reset() {
	*x = HandleExceptionReply{}
	mi := &file_helloworld_v1_kuai_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleExceptionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleExceptionReply) ProtoMessage() {}

func (x *HandleExceptionReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_kuai_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleExceptionReply.ProtoReflect.Descriptor instead.
func (*HandleExceptionReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_kuai_proto_rawDescGZIP(), []int{26}
}

func (x *HandleExceptionReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandleExceptionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HandleExceptionReply) GetNewStatus() OrderStatus {
	if x != nil {
		return x.NewStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *HandleExceptionReply) GetRequiresNegotiation() bool {
	if x != nil {
		return x.RequiresNegotiation
	}
	return false
}

func (x *HandleExceptionReply) GetSuggestedFee() float64 {
	if x != nil {
		return x.SuggestedFee
	}
	return 0
}

var File_helloworld_v1_kuai_proto protoreflect.FileDescriptor

const file_helloworld_v1_kuai_proto_rawDesc = "" +
	"\n" +
	"\x18helloworld/v1/kuai.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\")\n" +
	"\x12PerformanceRequest\x12\x13\n" +
	"\x05top_n\x18\x01 \x01(\x05R\x04topN\"K\n" +
	"\x10PerformanceReply\x127\n" +
	"\trank_list\x18\x01 \x03(\v2\x1a.helloworld.v1.CourierRankR\brankList\"\x90\x01\n" +
	"\vCourierRank\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x02 \x01(\x03R\tcourierId\x12!\n" +
	"\fcourier_name\x18\x03 \x01(\tR\vcourierName\x12+\n" +
	"\x11performance_score\x18\x04 \x01(\x01R\x10performanceScore\"\xff\a\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vsender_name\x18\x06 \x01(\tR\n" +
	"senderName\x12!\n" +
	"\fsender_phone\x18\a \x01(\tR\vsenderPhone\x12%\n" +
	"\x0esender_address\x18\b \x01(\tR\rsenderAddress\x12#\n" +
	"\rreceiver_name\x18\t \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\n" +
	" \x01(\tR\rreceiverPhone\x12)\n" +
	"\x10receiver_address\x18\v \x01(\tR\x0freceiverAddress\x12=\n" +
	"\fservice_type\x18\f \x01(\x0e2\x1a.helloworld.v1.ServiceTypeR\vserviceType\x12!\n" +
	"\fproduct_type\x18\r \x01(\tR\vproductType\x12\x1d\n" +
	"\n" +
	"is_insured\x18\x0e \x01(\x05R\tisInsured\x12#\n" +
	"\rinsured_value\x18\x0f \x01(\x01R\finsuredValue\x12)\n" +
	"\x10estimated_weight\x18\x10 \x01(\x01R\x0festimatedWeight\x12#\n" +
	"\ractual_weight\x18\x11 \x01(\x01R\factualWeight\x12#\n" +
	"\rvolume_weight\x18\x12 \x01(\x01R\fvolumeWeight\x12#\n" +
	"\restimated_fee\x18\x14 \x01(\x01R\festimatedFee\x12\x1d\n" +
	"\n" +
	"actual_fee\x18\x15 \x01(\x01R\tactualFee\x12C\n" +
	"\x0epayment_method\x18\x16 \x01(\x0e2\x1c.helloworld.v1.PaymentMethodR\rpaymentMethod\x12C\n" +
	"\x0epayment_status\x18\x17 \x01(\x0e2\x1c.helloworld.v1.PaymentStatusR\rpaymentStatus\x120\n" +
	"\x14expected_pickup_time\x18\x18 \x01(\x03R\x12expectedPickupTime\x12,\n" +
	"\x12actual_pickup_time\x18\x19 \x01(\x03R\x10actualPickupTime\x124\n" +
	"\x16expected_delivery_time\x18\x1a \x01(\x03R\x14expectedDeliveryTime\x120\n" +
	"\x14actual_delivery_time\x18\x1b \x01(\x03R\x12actualDeliveryTime\x12=\n" +
	"\forder_status\x18\x1c \x01(\x0e2\x1a.helloworld.v1.OrderStatusR\vorderStatus\"-\n" +
	"\x10CreateOrderReply\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"0\n" +
	"\x0fTakeTaskRequest\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x01 \x01(\x03R\tcourierId\"8\n" +
	"\rTakeTaskReply\x12'\n" +
	"\x04task\x18\x01 \x01(\v2\x13.helloworld.v1.TaskR\x04task\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xee\x01\n" +
	"\fGetTaskReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x02 \x01(\x03R\tcourierId\x12!\n" +
	"\fcourier_name\x18\x03 \x01(\tR\vcourierName\x124\n" +
	"\ttask_type\x18\x04 \x01(\x0e2\x17.helloworld.v1.TaskTypeR\btaskType\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12:\n" +
	"\vtask_status\x18\x06 \x01(\x0e2\x19.helloworld.v1.TaskStatusR\n" +
	"taskStatus\"=\n" +
	"\rStuUpdRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\x03R\x05phone\"%\n" +
	"\vStuUpdReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"L\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"\x1f\n" +
	"\rRegisterReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"\x1c\n" +
	"\n" +
	"LoginReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x11\n" +
	"\x0fTaskListRequest\"P\n" +
	"\rTaskListReply\x12)\n" +
	"\x05tasks\x18\x01 \x03(\v2\x13.helloworld.v1.TaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd7\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x02 \x01(\x03R\tcourierId\x12!\n" +
	"\fcourier_name\x18\x03 \x01(\tR\vcourierName\x124\n" +
	"\ttask_type\x18\x04 \x01(\x0e2\x17.helloworld.v1.TaskTypeR\btaskType\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12:\n" +
	"\vtask_status\x18\x06 \x01(\x0e2\x19.helloworld.v1.TaskStatusR\n" +
	"taskStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12%\n" +
	"\x0esender_address\x18\b \x01(\tR\rsenderAddress\x12)\n" +
	"\x10receiver_address\x18\t \x01(\tR\x0freceiverAddress\"\x13\n" +
	"\x11DeleteKuaiRequest\"\x11\n" +
	"\x0fDeleteKuaiReply\"\x10\n" +
	"\x0eGetKuaiRequest\"\x0e\n" +
	"\fGetKuaiReply\"\x12\n" +
	"\x10OrderListRequest\"\xa9\b\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12#\n" +
	"\rreceiver_name\x18\x04 \x01(\tR\freceiverName\x12!\n" +
	"\fservice_type\x18\x05 \x01(\tR\vserviceType\x12!\n" +
	"\forder_status\x18\x06 \x01(\tR\vorderStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x17\n" +
	"\auser_id\x18\b \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"courier_id\x18\t \x01(\x03R\tcourierId\x12!\n" +
	"\fsender_phone\x18\n" +
	" \x01(\tR\vsenderPhone\x12%\n" +
	"\x0esender_address\x18\v \x01(\tR\rsenderAddress\x12%\n" +
	"\x0ereceiver_phone\x18\f \x01(\tR\rreceiverPhone\x12)\n" +
	"\x10receiver_address\x18\r \x01(\tR\x0freceiverAddress\x12!\n" +
	"\fproduct_type\x18\x0e \x01(\tR\vproductType\x12\x1d\n" +
	"\n" +
	"is_insured\x18\x0f \x01(\x05R\tisInsured\x12#\n" +
	"\rinsured_value\x18\x10 \x01(\x01R\finsuredValue\x12)\n" +
	"\x10estimated_weight\x18\x11 \x01(\x01R\x0festimatedWeight\x12#\n" +
	"\ractual_weight\x18\x12 \x01(\x01R\factualWeight\x12#\n" +
	"\rvolume_weight\x18\x13 \x01(\x01R\fvolumeWeight\x12#\n" +
	"\restimated_fee\x18\x14 \x01(\x01R\festimatedFee\x12\x1d\n" +
	"\n" +
	"actual_fee\x18\x15 \x01(\x01R\tactualFee\x12%\n" +
	"\x0epayment_method\x18\x16 \x01(\tR\rpaymentMethod\x12%\n" +
	"\x0epayment_status\x18\x17 \x01(\tR\rpaymentStatus\x120\n" +
	"\x14expected_pickup_time\x18\x18 \x01(\x03R\x12expectedPickupTime\x12,\n" +
	"\x12actual_pickup_time\x18\x19 \x01(\x03R\x10actualPickupTime\x124\n" +
	"\x16expected_delivery_time\x18\x1a \x01(\x03R\x14expectedDeliveryTime\x120\n" +
	"\x14actual_delivery_time\x18\x1b \x01(\x03R\x12actualDeliveryTime\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x1c \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x1d \x01(\tR\tdeletedAt\">\n" +
	"\x0eOrderListReply\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.helloworld.v1.OrderItemR\x04list\"\xaf\x01\n" +
	"\x16HandleExceptionRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12C\n" +
	"\x0eexception_type\x18\x02 \x01(\x0e2\x1c.helloworld.v1.ExceptionTypeR\rexceptionType\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"courier_id\x18\x04 \x01(\x03R\tcourierId\"\xdd\x01\n" +
	"\x14HandleExceptionReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\n" +
	"new_status\x18\x03 \x01(\x0e2\x1a.helloworld.v1.OrderStatusR\tnewStatus\x121\n" +
	"\x14requires_negotiation\x18\x04 \x01(\bR\x13requiresNegotiation\x12#\n" +
	"\rsuggested_fee\x18\x05 \x01(\x01R\fsuggestedFee*\x84\x01\n" +
	"\vServiceType\x12\x1c\n" +
	"\x18DELIVERY_OPTION_SAME_DAY\x10\x00\x12\x1c\n" +
	"\x18DELIVERY_OPTION_NEXT_DAY\x10\x01\x12\x1c\n" +
	"\x18DELIVERY_OPTION_STANDARD\x10\x02\x12\x1b\n" +
	"\x17DELIVERY_OPTION_ECONOMY\x10\x03*\x8b\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PAYMENT_METHOD_SENDER_PAY\x10\x03\x12\x1f\n" +
	"\x1bPAYMENT_METHOD_RECEIVER_PAY\x10\x04\x12\x1a\n" +
	"\x16PAYMENT_METHOD_MONTHLY\x10\x05*\x9c\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13PAYMENT_STATUS_PAID\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x04*\x90\x02\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15ORDER_STATUS_ACCEPTED\x10\x02\x12\x1a\n" +
	"\x16ORDER_STATUS_PICKED_UP\x10\x03\x12\x1b\n" +
	"\x17ORDER_STATUS_IN_TRANSIT\x10\x04\x12!\n" +
	"\x1dORDER_STATUS_OUT_FOR_DELIVERY\x10\x05\x12\x1a\n" +
	"\x16ORDER_STATUS_DELIVERED\x10\x06\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\a\x12\x1a\n" +
	"\x16ORDER_STATUS_EXCEPTION\x10\b*?\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06Pickup\x10\x01\x12\f\n" +
	"\bDelivery\x10\x02*b\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPending\x10\x01\x12\f\n" +
	"\bAccepted\x10\x02\x12\r\n" +
	"\tCompleted\x10\x03\x12\r\n" +
	"\tCancelled\x10\x04*\xa3\x01\n" +
	"\rExceptionType\x12\x1e\n" +
	"\x1aEXCEPTION_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vUSER_CANCEL\x10\x01\x12\x12\n" +
	"\x0eCOURIER_CANCEL\x10\x02\x12\x13\n" +
	"\x0fDELIVERY_FAILED\x10\x03\x12\x11\n" +
	"\rPICKUP_FAILED\x10\x04\x12\x11\n" +
	"\rADDRESS_ERROR\x10\x05\x12\x12\n" +
	"\x0eCONTACT_FAILED\x10\x062\xb2\b\n" +
	"\x04Kuai\x12N\n" +
	"\n" +
	"DeleteKuai\x12 .helloworld.v1.DeleteKuaiRequest\x1a\x1e.helloworld.v1.DeleteKuaiReply\x12Z\n" +
	"\aGetTask\x12\x1d.helloworld.v1.GetTaskRequest\x1a\x1b.helloworld.v1.GetTaskReply\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/gettask\x12^\n" +
	"\bTaskList\x12\x1e.helloworld.v1.TaskListRequest\x1a\x1c.helloworld.v1.TaskListReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/taskList\x12R\n" +
	"\x05Login\x12\x1b.helloworld.v1.LoginRequest\x1a\x19.helloworld.v1.LoginReply\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/login\x12^\n" +
	"\bRegister\x12\x1e.helloworld.v1.RegisterRequest\x1a\x1c.helloworld.v1.RegisterReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/register\x12V\n" +
	"\x06StuUpd\x12\x1c.helloworld.v1.StuUpdRequest\x1a\x1a.helloworld.v1.StuUpdReply\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/stuUpd\x12]\n" +
	"\bTakeTask\x12\x1e.helloworld.v1.TakeTaskRequest\x1a\x1c.helloworld.v1.TakeTaskReply\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/addTask\x12j\n" +
	"\vCreateOrder\x12!.helloworld.v1.CreateOrderRequest\x1a\x1f.helloworld.v1.CreateOrderReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/createOrder\x12j\n" +
	"\vPerformance\x12!.helloworld.v1.PerformanceRequest\x1a\x1f.helloworld.v1.PerformanceReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/performance\x12_\n" +
	"\tOrderList\x12\x1f.helloworld.v1.OrderListRequest\x1a\x1d.helloworld.v1.OrderListReply\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/orders\x12z\n" +
	"\x0fHandleException\x12%.helloworld.v1.HandleExceptionRequest\x1a#.helloworld.v1.HandleExceptionReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/handleExceptionBX\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z#ShunFengParcel/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_kuai_proto_rawDescOnce sync.Once
	file_helloworld_v1_kuai_proto_rawDescData []byte
)

func file_helloworld_v1_kuai_proto_rawDescGZIP() []byte {
	file_helloworld_v1_kuai_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_kuai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_kuai_proto_rawDesc), len(file_helloworld_v1_kuai_proto_rawDesc)))
	})
	return file_helloworld_v1_kuai_proto_rawDescData
}

var file_helloworld_v1_kuai_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_helloworld_v1_kuai_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_helloworld_v1_kuai_proto_goTypes = []any{
	(ServiceType)(0),               // 0: helloworld.v1.ServiceType
	(PaymentMethod)(0),             // 1: helloworld.v1.PaymentMethod
	(PaymentStatus)(0),             // 2: helloworld.v1.PaymentStatus
	(OrderStatus)(0),               // 3: helloworld.v1.OrderStatus
	(TaskType)(0),                  // 4: helloworld.v1.TaskType
	(TaskStatus)(0),                // 5: helloworld.v1.TaskStatus
	(ExceptionType)(0),             // 6: helloworld.v1.ExceptionType
	(*PerformanceRequest)(nil),     // 7: helloworld.v1.PerformanceRequest
	(*PerformanceReply)(nil),       // 8: helloworld.v1.PerformanceReply
	(*CourierRank)(nil),            // 9: helloworld.v1.CourierRank
	(*CreateOrderRequest)(nil),     // 10: helloworld.v1.CreateOrderRequest
	(*CreateOrderReply)(nil),       // 11: helloworld.v1.CreateOrderReply
	(*TakeTaskRequest)(nil),        // 12: helloworld.v1.TakeTaskRequest
	(*TakeTaskReply)(nil),          // 13: helloworld.v1.TakeTaskReply
	(*GetTaskRequest)(nil),         // 14: helloworld.v1.GetTaskRequest
	(*GetTaskReply)(nil),           // 15: helloworld.v1.GetTaskReply
	(*StuUpdRequest)(nil),          // 16: helloworld.v1.StuUpdRequest
	(*StuUpdReply)(nil),            // 17: helloworld.v1.StuUpdReply
	(*RegisterRequest)(nil),        // 18: helloworld.v1.RegisterRequest
	(*RegisterReply)(nil),          // 19: helloworld.v1.RegisterReply
	(*LoginRequest)(nil),           // 20: helloworld.v1.LoginRequest
	(*LoginReply)(nil),             // 21: helloworld.v1.LoginReply
	(*TaskListRequest)(nil),        // 22: helloworld.v1.TaskListRequest
	(*TaskListReply)(nil),          // 23: helloworld.v1.TaskListReply
	(*Task)(nil),                   // 24: helloworld.v1.Task
	(*DeleteKuaiRequest)(nil),      // 25: helloworld.v1.DeleteKuaiRequest
	(*DeleteKuaiReply)(nil),        // 26: helloworld.v1.DeleteKuaiReply
	(*GetKuaiRequest)(nil),         // 27: helloworld.v1.GetKuaiRequest
	(*GetKuaiReply)(nil),           // 28: helloworld.v1.GetKuaiReply
	(*OrderListRequest)(nil),       // 29: helloworld.v1.OrderListRequest
	(*OrderItem)(nil),              // 30: helloworld.v1.OrderItem
	(*OrderListReply)(nil),         // 31: helloworld.v1.OrderListReply
	(*HandleExceptionRequest)(nil), // 32: helloworld.v1.HandleExceptionRequest
	(*HandleExceptionReply)(nil),   // 33: helloworld.v1.HandleExceptionReply
}
var file_helloworld_v1_kuai_proto_depIdxs = []int32{
	9,  // 0: helloworld.v1.PerformanceReply.rank_list:type_name -> helloworld.v1.CourierRank
	0,  // 1: helloworld.v1.CreateOrderRequest.service_type:type_name -> helloworld.v1.ServiceType
	1,  // 2: helloworld.v1.CreateOrderRequest.payment_method:type_name -> helloworld.v1.PaymentMethod
	2,  // 3: helloworld.v1.CreateOrderRequest.payment_status:type_name -> helloworld.v1.PaymentStatus
	3,  // 4: helloworld.v1.CreateOrderRequest.order_status:type_name -> helloworld.v1.OrderStatus
	24, // 5: helloworld.v1.TakeTaskReply.task:type_name -> helloworld.v1.Task
	4,  // 6: helloworld.v1.GetTaskReply.task_type:type_name -> helloworld.v1.TaskType
	5,  // 7: helloworld.v1.GetTaskReply.task_status:type_name -> helloworld.v1.TaskStatus
	24, // 8: helloworld.v1.TaskListReply.tasks:type_name -> helloworld.v1.Task
	4,  // 9: helloworld.v1.Task.task_type:type_name -> helloworld.v1.TaskType
	5,  // 10: helloworld.v1.Task.task_status:type_name -> helloworld.v1.TaskStatus
	30, // 11: helloworld.v1.OrderListReply.list:type_name -> helloworld.v1.OrderItem
	6,  // 12: helloworld.v1.HandleExceptionRequest.exception_type:type_name -> helloworld.v1.ExceptionType
	3,  // 13: helloworld.v1.HandleExceptionReply.new_status:type_name -> helloworld.v1.OrderStatus
	25, // 14: helloworld.v1.Kuai.DeleteKuai:input_type -> helloworld.v1.DeleteKuaiRequest
	14, // 15: helloworld.v1.Kuai.GetTask:input_type -> helloworld.v1.GetTaskRequest
	22, // 16: helloworld.v1.Kuai.TaskList:input_type -> helloworld.v1.TaskListRequest
	20, // 17: helloworld.v1.Kuai.Login:input_type -> helloworld.v1.LoginRequest
	18, // 18: helloworld.v1.Kuai.Register:input_type -> helloworld.v1.RegisterRequest
	16, // 19: helloworld.v1.Kuai.StuUpd:input_type -> helloworld.v1.StuUpdRequest
	12, // 20: helloworld.v1.Kuai.TakeTask:input_type -> helloworld.v1.TakeTaskRequest
	10, // 21: helloworld.v1.Kuai.CreateOrder:input_type -> helloworld.v1.CreateOrderRequest
	7,  // 22: helloworld.v1.Kuai.Performance:input_type -> helloworld.v1.PerformanceRequest
	29, // 23: helloworld.v1.Kuai.OrderList:input_type -> helloworld.v1.OrderListRequest
	32, // 24: helloworld.v1.Kuai.HandleException:input_type -> helloworld.v1.HandleExceptionRequest
	26, // 25: helloworld.v1.Kuai.DeleteKuai:output_type -> helloworld.v1.DeleteKuaiReply
	15, // 26: helloworld.v1.Kuai.GetTask:output_type -> helloworld.v1.GetTaskReply
	23, // 27: helloworld.v1.Kuai.TaskList:output_type -> helloworld.v1.TaskListReply
	21, // 28: helloworld.v1.Kuai.Login:output_type -> helloworld.v1.LoginReply
	19, // 29: helloworld.v1.Kuai.Register:output_type -> helloworld.v1.RegisterReply
	17, // 30: helloworld.v1.Kuai.StuUpd:output_type -> helloworld.v1.StuUpdReply
	13, // 31: helloworld.v1.Kuai.TakeTask:output_type -> helloworld.v1.TakeTaskReply
	11, // 32: helloworld.v1.Kuai.CreateOrder:output_type -> helloworld.v1.CreateOrderReply
	8,  // 33: helloworld.v1.Kuai.Performance:output_type -> helloworld.v1.PerformanceReply
	31, // 34: helloworld.v1.Kuai.OrderList:output_type -> helloworld.v1.OrderListReply
	33, // 35: helloworld.v1.Kuai.HandleException:output_type -> helloworld.v1.HandleExceptionReply
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_helloworld_v1_kuai_proto_init() }
func file_helloworld_v1_kuai_proto_init() {
	if File_helloworld_v1_kuai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_kuai_proto_rawDesc), len(file_helloworld_v1_kuai_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_kuai_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_kuai_proto_depIdxs,
		EnumInfos:         file_helloworld_v1_kuai_proto_enumTypes,
		MessageInfos:      file_helloworld_v1_kuai_proto_msgTypes,
	}.Build()
	File_helloworld_v1_kuai_proto = out.File
	file_helloworld_v1_kuai_proto_goTypes = nil
	file_helloworld_v1_kuai_proto_depIdxs = nil
}
