// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.11
// source: api/helloworld/v1/order.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type AddOrderReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Userid          int64                  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Courierid       int64                  `protobuf:"varint,2,opt,name=courierid,proto3" json:"courierid,omitempty"`
	Sendername      string                 `protobuf:"bytes,3,opt,name=sendername,proto3" json:"sendername,omitempty"`
	Senderphone     string                 `protobuf:"bytes,4,opt,name=senderphone,proto3" json:"senderphone,omitempty"`
	Senderaddress   string                 `protobuf:"bytes,5,opt,name=senderaddress,proto3" json:"senderaddress,omitempty"`
	Receivername    string                 `protobuf:"bytes,6,opt,name=receivername,proto3" json:"receivername,omitempty"`
	Receiverphone   string                 `protobuf:"bytes,7,opt,name=receiverphone,proto3" json:"receiverphone,omitempty"`
	Receiveraddress string                 `protobuf:"bytes,8,opt,name=receiveraddress,proto3" json:"receiveraddress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddOrderReq) Reset() {
	*x = AddOrderReq{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderReq) ProtoMessage() {}

func (x *AddOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderReq.ProtoReflect.Descriptor instead.
func (*AddOrderReq) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *AddOrderReq) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *AddOrderReq) GetCourierid() int64 {
	if x != nil {
		return x.Courierid
	}
	return 0
}

func (x *AddOrderReq) GetSendername() string {
	if x != nil {
		return x.Sendername
	}
	return ""
}

func (x *AddOrderReq) GetSenderphone() string {
	if x != nil {
		return x.Senderphone
	}
	return ""
}

func (x *AddOrderReq) GetSenderaddress() string {
	if x != nil {
		return x.Senderaddress
	}
	return ""
}

func (x *AddOrderReq) GetReceivername() string {
	if x != nil {
		return x.Receivername
	}
	return ""
}

func (x *AddOrderReq) GetReceiverphone() string {
	if x != nil {
		return x.Receiverphone
	}
	return ""
}

func (x *AddOrderReq) GetReceiveraddress() string {
	if x != nil {
		return x.Receiveraddress
	}
	return ""
}

// The response message containing the greetings
type AddOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrderResp) Reset() {
	*x = AddOrderResp{}
	mi := &file_api_helloworld_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrderResp) ProtoMessage() {}

func (x *AddOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrderResp.ProtoReflect.Descriptor instead.
func (*AddOrderResp) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *AddOrderResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_api_helloworld_v1_order_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/helloworld/v1/order.proto\x12\x06stream\x1a\x1cgoogle/api/annotations.proto\"\x9f\x02\n" +
	"\vAddOrderReq\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\x03R\x06userid\x12\x1c\n" +
	"\tcourierid\x18\x02 \x01(\x03R\tcourierid\x12\x1e\n" +
	"\n" +
	"sendername\x18\x03 \x01(\tR\n" +
	"sendername\x12 \n" +
	"\vsenderphone\x18\x04 \x01(\tR\vsenderphone\x12$\n" +
	"\rsenderaddress\x18\x05 \x01(\tR\rsenderaddress\x12\"\n" +
	"\freceivername\x18\x06 \x01(\tR\freceivername\x12$\n" +
	"\rreceiverphone\x18\a \x01(\tR\rreceiverphone\x12(\n" +
	"\x0freceiveraddress\x18\b \x01(\tR\x0freceiveraddress\"\x1e\n" +
	"\fAddOrderResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2S\n" +
	"\x05Order\x12J\n" +
	"\bAddOrder\x12\x13.stream.AddOrderReq\x1a\x14.stream.AddOrderResp\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\baddorderBX\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z#ShunFengParcel/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_order_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_order_proto_rawDescData []byte
)

func file_api_helloworld_v1_order_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_order_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_order_proto_rawDesc), len(file_api_helloworld_v1_order_proto_rawDesc)))
	})
	return file_api_helloworld_v1_order_proto_rawDescData
}

var file_api_helloworld_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_helloworld_v1_order_proto_goTypes = []any{
	(*AddOrderReq)(nil),  // 0: stream.AddOrderReq
	(*AddOrderResp)(nil), // 1: stream.AddOrderResp
}
var file_api_helloworld_v1_order_proto_depIdxs = []int32{
	0, // 0: stream.Order.AddOrder:input_type -> stream.AddOrderReq
	1, // 1: stream.Order.AddOrder:output_type -> stream.AddOrderResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_order_proto_init() }
func file_api_helloworld_v1_order_proto_init() {
	if File_api_helloworld_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_order_proto_rawDesc), len(file_api_helloworld_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_order_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_order_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_order_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_order_proto = out.File
	file_api_helloworld_v1_order_proto_goTypes = nil
	file_api_helloworld_v1_order_proto_depIdxs = nil
}
