// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.11
// source: helloworld/v1/wei.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type WXRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WXRequest) Reset() {
	*x = WXRequest{}
	mi := &file_helloworld_v1_wei_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WXRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WXRequest) ProtoMessage() {}

func (x *WXRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_wei_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WXRequest.ProtoReflect.Descriptor instead.
func (*WXRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_wei_proto_rawDescGZIP(), []int{0}
}

// The response message containing the greetings
type WXReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WXReply) Reset() {
	*x = WXReply{}
	mi := &file_helloworld_v1_wei_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WXReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WXReply) ProtoMessage() {}

func (x *WXReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_wei_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WXReply.ProtoReflect.Descriptor instead.
func (*WXReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_wei_proto_rawDescGZIP(), []int{1}
}

// The request message containing the user's name.
type WechatLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatLoginRequest) Reset() {
	*x = WechatLoginRequest{}
	mi := &file_helloworld_v1_wei_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatLoginRequest) ProtoMessage() {}

func (x *WechatLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_wei_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatLoginRequest.ProtoReflect.Descriptor instead.
func (*WechatLoginRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_wei_proto_rawDescGZIP(), []int{2}
}

// The response message containing the greetings
type WechatLoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WechatLoginReply) Reset() {
	*x = WechatLoginReply{}
	mi := &file_helloworld_v1_wei_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WechatLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatLoginReply) ProtoMessage() {}

func (x *WechatLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_wei_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatLoginReply.ProtoReflect.Descriptor instead.
func (*WechatLoginReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_wei_proto_rawDescGZIP(), []int{3}
}

// The request message containing the user's name.
type CallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackRequest) Reset() {
	*x = CallbackRequest{}
	mi := &file_helloworld_v1_wei_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackRequest) ProtoMessage() {}

func (x *CallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_wei_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackRequest.ProtoReflect.Descriptor instead.
func (*CallbackRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_wei_proto_rawDescGZIP(), []int{4}
}

// The response message containing the greetings
type CallbackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackReply) Reset() {
	*x = CallbackReply{}
	mi := &file_helloworld_v1_wei_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackReply) ProtoMessage() {}

func (x *CallbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_wei_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackReply.ProtoReflect.Descriptor instead.
func (*CallbackReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_wei_proto_rawDescGZIP(), []int{5}
}

var File_helloworld_v1_wei_proto protoreflect.FileDescriptor

const file_helloworld_v1_wei_proto_rawDesc = "" +
	"\n" +
	"\x17helloworld/v1/wei.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"\v\n" +
	"\tWXRequest\"\t\n" +
	"\aWXReply\"\x14\n" +
	"\x12WechatLoginRequest\"\x12\n" +
	"\x10WechatLoginReply\"\x11\n" +
	"\x0fCallbackRequest\"\x0f\n" +
	"\rCallbackReply2\x90\x02\n" +
	"\x03Wei\x12C\n" +
	"\x02WX\x12\x18.helloworld.v1.WXRequest\x1a\x16.helloworld.v1.WXReply\"\v\x82\xd3\xe4\x93\x02\x05\x12\x03/wx\x12g\n" +
	"\vWechatLogin\x12!.helloworld.v1.WechatLoginRequest\x1a\x1f.helloworld.v1.WechatLoginReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/wechatLogin\x12[\n" +
	"\bCallback\x12\x1e.helloworld.v1.CallbackRequest\x1a\x1c.helloworld.v1.CallbackReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/callbackBm\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloWorldProtoV1P\x01Z8github.com/go-kratos/service-layout/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_wei_proto_rawDescOnce sync.Once
	file_helloworld_v1_wei_proto_rawDescData []byte
)

func file_helloworld_v1_wei_proto_rawDescGZIP() []byte {
	file_helloworld_v1_wei_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_wei_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_wei_proto_rawDesc), len(file_helloworld_v1_wei_proto_rawDesc)))
	})
	return file_helloworld_v1_wei_proto_rawDescData
}

var file_helloworld_v1_wei_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_helloworld_v1_wei_proto_goTypes = []any{
	(*WXRequest)(nil),          // 0: helloworld.v1.WXRequest
	(*WXReply)(nil),            // 1: helloworld.v1.WXReply
	(*WechatLoginRequest)(nil), // 2: helloworld.v1.WechatLoginRequest
	(*WechatLoginReply)(nil),   // 3: helloworld.v1.WechatLoginReply
	(*CallbackRequest)(nil),    // 4: helloworld.v1.CallbackRequest
	(*CallbackReply)(nil),      // 5: helloworld.v1.CallbackReply
}
var file_helloworld_v1_wei_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Wei.WX:input_type -> helloworld.v1.WXRequest
	2, // 1: helloworld.v1.Wei.WechatLogin:input_type -> helloworld.v1.WechatLoginRequest
	4, // 2: helloworld.v1.Wei.Callback:input_type -> helloworld.v1.CallbackRequest
	1, // 3: helloworld.v1.Wei.WX:output_type -> helloworld.v1.WXReply
	3, // 4: helloworld.v1.Wei.WechatLogin:output_type -> helloworld.v1.WechatLoginReply
	5, // 5: helloworld.v1.Wei.Callback:output_type -> helloworld.v1.CallbackReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_v1_wei_proto_init() }
func file_helloworld_v1_wei_proto_init() {
	if File_helloworld_v1_wei_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_wei_proto_rawDesc), len(file_helloworld_v1_wei_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_wei_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_wei_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_wei_proto_msgTypes,
	}.Build()
	File_helloworld_v1_wei_proto = out.File
	file_helloworld_v1_wei_proto_goTypes = nil
	file_helloworld_v1_wei_proto_depIdxs = nil
}
