// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v3.21.11
// source: helloworld/v1/wei.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWeiCallback = "/helloworld.v1.Wei/Callback"
const OperationWeiWX = "/helloworld.v1.Wei/WX"
const OperationWeiWechatLogin = "/helloworld.v1.Wei/WechatLogin"

type WeiHTTPServer interface {
	Callback(context.Context, *CallbackRequest) (*CallbackReply, error)
	// WX Sends a greeting
	WX(context.Context, *WXRequest) (*WXReply, error)
	WechatLogin(context.Context, *WechatLoginRequest) (*WechatLoginReply, error)
}

func RegisterWeiHTTPServer(s *http.Server, srv WeiHTTPServer) {
	r := s.Route("/")
	r.GET("/wx", _Wei_WX0_HTTP_Handler(srv))
	r.GET("/wechatLogin", _Wei_WechatLogin0_HTTP_Handler(srv))
	r.GET("/callback", _Wei_Callback0_HTTP_Handler(srv))
}

func _Wei_WX0_HTTP_Handler(srv WeiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WXRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWeiWX)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WX(ctx, req.(*WXRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WXReply)
		return ctx.Result(200, reply)
	}
}

func _Wei_WechatLogin0_HTTP_Handler(srv WeiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WechatLoginRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWeiWechatLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WechatLogin(ctx, req.(*WechatLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WechatLoginReply)
		return ctx.Result(200, reply)
	}
}

func _Wei_Callback0_HTTP_Handler(srv WeiHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CallbackRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWeiCallback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Callback(ctx, req.(*CallbackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CallbackReply)
		return ctx.Result(200, reply)
	}
}

type WeiHTTPClient interface {
	Callback(ctx context.Context, req *CallbackRequest, opts ...http.CallOption) (rsp *CallbackReply, err error)
	// WX Sends a greeting
	WX(ctx context.Context, req *WXRequest, opts ...http.CallOption) (rsp *WXReply, err error)
	WechatLogin(ctx context.Context, req *WechatLoginRequest, opts ...http.CallOption) (rsp *WechatLoginReply, err error)
}

type WeiHTTPClientImpl struct {
	cc *http.Client
}

func NewWeiHTTPClient(client *http.Client) WeiHTTPClient {
	return &WeiHTTPClientImpl{client}
}

func (c *WeiHTTPClientImpl) Callback(ctx context.Context, in *CallbackRequest, opts ...http.CallOption) (*CallbackReply, error) {
	var out CallbackReply
	pattern := "/callback"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWeiCallback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// WX Sends a greeting
func (c *WeiHTTPClientImpl) WX(ctx context.Context, in *WXRequest, opts ...http.CallOption) (*WXReply, error) {
	var out WXReply
	pattern := "/wx"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWeiWX))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WeiHTTPClientImpl) WechatLogin(ctx context.Context, in *WechatLoginRequest, opts ...http.CallOption) (*WechatLoginReply, error) {
	var out WechatLoginReply
	pattern := "/wechatLogin"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWeiWechatLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
