// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.11
// source: helloworld/v1/wei.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Wei_WX_FullMethodName          = "/helloworld.v1.Wei/WX"
	Wei_WechatLogin_FullMethodName = "/helloworld.v1.Wei/WechatLogin"
	Wei_Callback_FullMethodName    = "/helloworld.v1.Wei/Callback"
)

// WeiClient is the client API for Wei service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type WeiClient interface {
	// Sends a greeting
	WX(ctx context.Context, in *WXRequest, opts ...grpc.CallOption) (*WXReply, error)
	WechatLogin(ctx context.Context, in *WechatLoginRequest, opts ...grpc.CallOption) (*WechatLoginReply, error)
	Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackReply, error)
}

type weiClient struct {
	cc grpc.ClientConnInterface
}

func NewWeiClient(cc grpc.ClientConnInterface) WeiClient {
	return &weiClient{cc}
}

func (c *weiClient) WX(ctx context.Context, in *WXRequest, opts ...grpc.CallOption) (*WXReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WXReply)
	err := c.cc.Invoke(ctx, Wei_WX_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weiClient) WechatLogin(ctx context.Context, in *WechatLoginRequest, opts ...grpc.CallOption) (*WechatLoginReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WechatLoginReply)
	err := c.cc.Invoke(ctx, Wei_WechatLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weiClient) Callback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallbackReply)
	err := c.cc.Invoke(ctx, Wei_Callback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeiServer is the server API for Wei service.
// All implementations must embed UnimplementedWeiServer
// for forward compatibility.
//
// The greeting service definition.
type WeiServer interface {
	// Sends a greeting
	WX(context.Context, *WXRequest) (*WXReply, error)
	WechatLogin(context.Context, *WechatLoginRequest) (*WechatLoginReply, error)
	Callback(context.Context, *CallbackRequest) (*CallbackReply, error)
	mustEmbedUnimplementedWeiServer()
}

// UnimplementedWeiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeiServer struct{}

func (UnimplementedWeiServer) WX(context.Context, *WXRequest) (*WXReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WX not implemented")
}
func (UnimplementedWeiServer) WechatLogin(context.Context, *WechatLoginRequest) (*WechatLoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WechatLogin not implemented")
}
func (UnimplementedWeiServer) Callback(context.Context, *CallbackRequest) (*CallbackReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Callback not implemented")
}
func (UnimplementedWeiServer) mustEmbedUnimplementedWeiServer() {}
func (UnimplementedWeiServer) testEmbeddedByValue()             {}

// UnsafeWeiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeiServer will
// result in compilation errors.
type UnsafeWeiServer interface {
	mustEmbedUnimplementedWeiServer()
}

func RegisterWeiServer(s grpc.ServiceRegistrar, srv WeiServer) {
	// If the following call pancis, it indicates UnimplementedWeiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Wei_ServiceDesc, srv)
}

func _Wei_WX_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WXRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeiServer).WX(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wei_WX_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeiServer).WX(ctx, req.(*WXRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wei_WechatLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WechatLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeiServer).WechatLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wei_WechatLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeiServer).WechatLogin(ctx, req.(*WechatLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wei_Callback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeiServer).Callback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Wei_Callback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeiServer).Callback(ctx, req.(*CallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wei_ServiceDesc is the grpc.ServiceDesc for Wei service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wei_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.v1.Wei",
	HandlerType: (*WeiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WX",
			Handler:    _Wei_WX_Handler,
		},
		{
			MethodName: "WechatLogin",
			Handler:    _Wei_WechatLogin_Handler,
		},
		{
			MethodName: "Callback",
			Handler:    _Wei_Callback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/v1/wei.proto",
}
