server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:mysql_8tDfmn@tcp(14.103.136.136:3306)/shunfeng?parseTime=True&loc=Local
  redis:
    addr: 14.103.136.136:6379
    password: mysql_8tDfmn
    read_timeout: 0.2s
    write_timeout: 0.2s
